/*
 * Copyright (c) 2026 RusTokRs.
 *
 * This file is part of RusTok.
 * Licensed under the Business Source License 1.1 with RusTok Additional Use Grant.
 * See the LICENSE file in the project root for full license terms.
 *
 * You may not remove or alter this copyright notice or license header.
 */

/// Helper macro for constructing `FluentArgs`.
/// Supports both:
/// - `fluent_args!(name = val, count = count)`
/// - `fluent_args!("name" => val, "count" => count)`
///
/// Consumer-style use works through a renamed crate import because the macro
/// resolves Fluent types through `$crate` internally:
/// ```
/// use rustok_ui_i18n as i18n;
///
/// let name = "Ada";
/// let _args = i18n::fluent_args!(name = name, count = 2);
/// let _string_key_args = i18n::fluent_args!("name" => name);
/// ```
///
/// Invalid key/value syntax is a compile-time error:
/// ```compile_fail
/// let _args = rustok_ui_i18n::fluent_args!(count);
/// ```
#[macro_export]
macro_rules! fluent_args {
    ($($key:ident = $val:expr),* $(,)?) => {{
        let mut args = $crate::FluentArgs::new();
        $(
            args.set(stringify!($key), $crate::FluentValue::from($val));
        )*
        args
    }};
    ($($key:expr => $val:expr),* $(,)?) => {{
        let mut args = $crate::FluentArgs::new();
        $(
            args.set($key, $crate::FluentValue::from($val));
        )*
        args
    }};
}

/// Global macro for resolving messages against a specified `UiMessages` reference.
#[macro_export]
macro_rules! t {
    ($messages:expr, $locale:expr, $key:expr, $fallback:expr) => {
        $messages.t_for_locale($locale, $key, $fallback)
    };
    ($messages:expr, $locale:expr, $key:expr, $fallback:expr, $($arg_name:ident = $arg_val:expr),+ $(,)?) => {
        $messages.format(
            $locale,
            $key,
            Some(&$crate::fluent_args!($($arg_name = $arg_val),+)),
            $fallback,
        )
    };
    ($messages:expr, $locale:expr, $key:expr, $fallback:expr, $($arg_name:expr => $arg_val:expr),+ $(,)?) => {
        $messages.format(
            $locale,
            $key,
            Some(&$crate::fluent_args!($($arg_name => $arg_val),+)),
            $fallback,
        )
    };
}

/// Resolves messages against the module-local `MESSAGES` catalog generated by
/// [`declare_module_i18n!`].
///
/// Calling the macro without a module-local catalog is intentionally rejected
/// by normal Rust name resolution:
/// ```compile_fail
/// let _ = rustok_ui_i18n::module_t!(Some("en"), "title", "fallback");
/// ```
#[macro_export]
macro_rules! module_t {
    ($locale:expr, $key:expr, $fallback:expr) => {
        $crate::t!(MESSAGES, $locale, $key, $fallback)
    };
    ($locale:expr, $key:expr, $fallback:expr, $($arg_name:ident = $arg_val:expr),+ $(,)?) => {
        $crate::t!(
            MESSAGES,
            $locale,
            $key,
            $fallback,
            $($arg_name = $arg_val),+
        )
    };
    ($locale:expr, $key:expr, $fallback:expr, $($arg_name:expr => $arg_val:expr),+ $(,)?) => {
        $crate::t!(
            MESSAGES,
            $locale,
            $key,
            $fallback,
            $($arg_name => $arg_val),+
        )
    };
}

/// Declares canonical module-owned i18n catalogs and accessor functions.
///
/// Default invocation (loads `../locales/en.ftl` and `../locales/ru.ftl`):
/// ```ignore
/// rustok_ui_i18n::declare_module_i18n!();
/// ```
///
/// A module can include any explicit set of locale files without hardcoding an
/// `en`/`ru` pair in generated code:
/// ```ignore
/// rustok_ui_i18n::declare_module_i18n!(
///     default = "en",
///     locales = ["en", "ar", "de", "es-419", "ja", "zh-Hant"],
/// );
/// ```
///
/// Large embedded catalogs can opt into per-locale FTL parsing on first use:
/// ```ignore
/// rustok_ui_i18n::declare_module_i18n!(
///     lazy,
///     default = "en",
///     locales = ["en", "ar", "de", "es-419", "ja", "zh-Hant"],
/// );
/// ```
/// This avoids eagerly constructing every Fluent bundle, but `include_str!` bytes
/// remain embedded in the binary. `validate()` still checks the complete catalog.
///
/// Custom invocation from an external consumer, including a renamed crate import:
/// ```
/// mod consumer {
///     use rustok_ui_i18n as i18n;
///
///     const EN: &str = "hello = Hello\n";
///     i18n::declare_module_i18n!("en", &[("en", EN)]);
///
///     pub fn render() -> String {
///         i18n::module_t!(Some("en"), "hello", "fallback")
///     }
/// }
///
/// assert_eq!(consumer::render(), "Hello");
/// ```
///
/// Unsupported invocation forms fail at compile time rather than silently
/// selecting an implicit configuration:
/// ```compile_fail
/// rustok_ui_i18n::declare_module_i18n!("en");
/// ```
#[macro_export]
macro_rules! declare_module_i18n {
    () => {
        $crate::declare_module_i18n!(
            "en",
            &[
                ("en", include_str!("../locales/en.ftl")),
                ("ru", include_str!("../locales/ru.ftl")),
            ]
        );
    };
    (
        lazy,
        default = $default_locale:literal,
        locales = [$($locale:literal),+ $(,)?]
        $(,)?
    ) => {
        $crate::declare_module_i18n!(
            lazy,
            $default_locale,
            &[
                $(
                    (
                        $locale,
                        include_str!(concat!("../locales/", $locale, ".ftl")),
                    ),
                )+
            ]
        );
    };
    (
        default = $default_locale:literal,
        locales = [$($locale:literal),+ $(,)?]
        $(,)?
    ) => {
        $crate::declare_module_i18n!(
            $default_locale,
            &[
                $(
                    (
                        $locale,
                        include_str!(concat!("../locales/", $locale, ".ftl")),
                    ),
                )+
            ]
        );
    };
    (lazy, $default_locale:expr, $bundles:expr) => {
        $crate::declare_module_i18n!(
            @declare,
            $crate::LazyUiMessages,
            $default_locale,
            $bundles
        );
    };
    ($default_locale:expr, $bundles:expr) => {
        $crate::declare_module_i18n!(
            @declare,
            $crate::UiMessages,
            $default_locale,
            $bundles
        );
    };
    (@declare, $messages_type:ty, $default_locale:expr, $bundles:expr) => {
        static MESSAGES: $messages_type = <$messages_type>::new($default_locale, $bundles);

        #[inline]
        pub fn t(locale: Option<&str>, key: &str, fallback: &str) -> String {
            MESSAGES.t_for_locale(locale, key, fallback)
        }

        #[inline]
        pub fn format<'args>(
            locale: Option<&str>,
            key: &str,
            args: Option<&$crate::FluentArgs<'args>>,
            fallback: &str,
        ) -> String {
            MESSAGES.format(locale, key, args, fallback)
        }

        #[inline]
        pub fn format_attribute<'args>(
            locale: Option<&str>,
            key: &str,
            attribute: &str,
            args: Option<&$crate::FluentArgs<'args>>,
            fallback: &str,
        ) -> String {
            MESSAGES.format_attribute(locale, key, attribute, args, fallback)
        }

        /// Validates the complete embedded catalog using fail-closed semantics.
        #[inline]
        pub fn validate() -> Result<(), $crate::BundleBuildError> {
            MESSAGES.validate()
        }

        /// Returns typed diagnostics from catalog initialization.
        #[inline]
        pub fn initialization_diagnostics() -> &'static [$crate::BundleBuildError] {
            MESSAGES.initialization_diagnostics()
        }

        /// Fail-closed catalog contract for the declaring package.
        ///
        /// Strict validation used to be reachable only if a package chose to
        /// call `validate()` itself, and no package in the workspace did. The
        /// macro therefore generates the gate so every declared catalog is
        /// checked for FTL syntax, duplicate entries, unresolved and cyclic
        /// message/term references, a present and canonical default locale,
        /// and cross-locale value/attribute variable parity.
        #[cfg(test)]
        // The macro is normally invoked at the top of a module that defines
        // further helpers below it, so the generated test module is not the
        // last item in the file.
        #[allow(clippy::items_after_test_module)]
        mod generated_module_i18n_contract {
            #[test]
            fn declared_catalog_is_valid() {
                if let Err(error) = super::validate() {
                    panic!("module i18n catalog failed strict validation: {error}");
                }
            }

            #[test]
            fn declared_catalog_initializes_without_diagnostics() {
                let diagnostics = super::initialization_diagnostics();
                assert!(
                    diagnostics.is_empty(),
                    "module i18n catalog reported initialization diagnostics: {diagnostics:?}"
                );
            }
        }
    };
}
