/*
 * Copyright (c) 2026 RusTokRs.
 *
 * This file is part of RusTok.
 * Licensed under the Business Source License 1.1 with RusTok Additional Use Grant.
 * See the LICENSE file in the project root for full license terms.
 *
 * You may not remove or alter this copyright notice or license header.
 */

/// Helper macro for constructing `FluentArgs`.
/// Supports both:
/// - `fluent_args!(name = val, count = count)`
/// - `fluent_args!("name" => val, "count" => count)`
///
/// Consumer-style use works through a renamed crate import because the macro
/// resolves Fluent types through `$crate` internally:
/// ```
/// use rustok_ui_i18n as i18n;
///
/// let name = "Ada";
/// let _args = i18n::fluent_args!(name = name, count = 2);
/// let _string_key_args = i18n::fluent_args!("name" => name);
/// ```
///
/// Invalid key/value syntax is a compile-time error:
/// ```compile_fail
/// let _args = rustok_ui_i18n::fluent_args!(count);
/// ```
#[macro_export]
macro_rules! fluent_args {
    ($($key:ident = $val:expr),* $(,)?) => {{
        let mut args = $crate::FluentArgs::new();
        $(
            args.set(stringify!($key), $crate::FluentValue::from($val));
        )*
        args
    }};
    ($($key:expr => $val:expr),* $(,)?) => {{
        let mut args = $crate::FluentArgs::new();
        $(
            args.set($key, $crate::FluentValue::from($val));
        )*
        args
    }};
}

/// Global macro for resolving messages against a specified `UiMessages` reference.
#[macro_export]
macro_rules! t {
    ($messages:expr, $locale:expr, $key:expr, $fallback:expr) => {
        $messages.t_for_locale($locale, $key, $fallback)
    };
    ($messages:expr, $locale:expr, $key:expr, $fallback:expr, $($arg_name:ident = $arg_val:expr),+ $(,)?) => {
        $messages.format(
            $locale,
            $key,
            Some(&$crate::fluent_args!($($arg_name = $arg_val),+)),
            $fallback,
        )
    };
    ($messages:expr, $locale:expr, $key:expr, $fallback:expr, $($arg_name:expr => $arg_val:expr),+ $(,)?) => {
        $messages.format(
            $locale,
            $key,
            Some(&$crate::fluent_args!($($arg_name => $arg_val),+)),
            $fallback,
        )
    };
}

/// Resolves messages against the module-local `MESSAGES` catalog generated by
/// [`declare_module_i18n!`].
///
/// Calling the macro without a module-local catalog is intentionally rejected
/// by normal Rust name resolution:
/// ```compile_fail
/// let _ = rustok_ui_i18n::module_t!(Some("en"), "title", "fallback");
/// ```
#[macro_export]
macro_rules! module_t {
    ($locale:expr, $key:expr, $fallback:expr) => {
        $crate::t!(MESSAGES, $locale, $key, $fallback)
    };
    ($locale:expr, $key:expr, $fallback:expr, $($arg_name:ident = $arg_val:expr),+ $(,)?) => {
        $crate::t!(
            MESSAGES,
            $locale,
            $key,
            $fallback,
            $($arg_name = $arg_val),+
        )
    };
    ($locale:expr, $key:expr, $fallback:expr, $($arg_name:expr => $arg_val:expr),+ $(,)?) => {
        $crate::t!(
            MESSAGES,
            $locale,
            $key,
            $fallback,
            $($arg_name => $arg_val),+
        )
    };
}

/// Declares canonical module-owned i18n catalogs and accessor functions.
///
/// Default invocation (loads `../locales/en.ftl` and `../locales/ru.ftl`):
/// ```ignore
/// rustok_ui_i18n::declare_module_i18n!();
/// ```
///
/// Custom invocation from an external consumer, including a renamed crate import:
/// ```
/// mod consumer {
///     use rustok_ui_i18n as i18n;
///
///     const EN: &str = "hello = Hello\n";
///     i18n::declare_module_i18n!("en", &[("en", EN)]);
///
///     pub fn render() -> String {
///         i18n::module_t!(Some("en"), "hello", "fallback")
///     }
/// }
///
/// assert_eq!(consumer::render(), "Hello");
/// ```
///
/// Unsupported invocation forms fail at compile time rather than silently
/// selecting an implicit configuration:
/// ```compile_fail
/// rustok_ui_i18n::declare_module_i18n!("en");
/// ```
#[macro_export]
macro_rules! declare_module_i18n {
    () => {
        $crate::declare_module_i18n!(
            "en",
            &[
                ("en", include_str!("../locales/en.ftl")),
                ("ru", include_str!("../locales/ru.ftl")),
            ]
        );
    };
    ($default_locale:expr, $bundles:expr) => {
        static MESSAGES: $crate::UiMessages = $crate::UiMessages::new($default_locale, $bundles);

        #[inline]
        pub fn t(locale: Option<&str>, key: &str, fallback: &str) -> String {
            MESSAGES.t_for_locale(locale, key, fallback)
        }

        #[inline]
        pub fn format<'args>(
            locale: Option<&str>,
            key: &str,
            args: Option<&$crate::FluentArgs<'args>>,
            fallback: &str,
        ) -> String {
            MESSAGES.format(locale, key, args, fallback)
        }
    };
}
