use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(AiProviderProfiles::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AiProviderProfiles::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::Slug)
                            .string_len(96)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::DisplayName)
                            .string_len(160)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::ProviderKind)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::BaseUrl)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::Model)
                            .string_len(160)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::ApiKeySecret)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::Temperature)
                            .float()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::MaxTokens)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::IsActive)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(ColumnDef::new(AiProviderProfiles::CreatedBy).uuid().null())
                    .col(ColumnDef::new(AiProviderProfiles::UpdatedBy).uuid().null())
                    .col(
                        ColumnDef::new(AiProviderProfiles::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(AiProviderProfiles::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiProviderProfiles::Table, AiProviderProfiles::TenantId)
                            .to(Alias::new("tenants"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_ai_provider_profiles_tenant_slug")
                    .table(AiProviderProfiles::Table)
                    .unique()
                    .col(AiProviderProfiles::TenantId)
                    .col(AiProviderProfiles::Slug)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AiToolProfiles::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AiToolProfiles::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(AiToolProfiles::TenantId).uuid().not_null())
                    .col(
                        ColumnDef::new(AiToolProfiles::Slug)
                            .string_len(96)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiToolProfiles::DisplayName)
                            .string_len(160)
                            .not_null(),
                    )
                    .col(ColumnDef::new(AiToolProfiles::Description).text().null())
                    .col(
                        ColumnDef::new(AiToolProfiles::AllowedTools)
                            .json_binary()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(AiToolProfiles::DeniedTools)
                            .json_binary()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(AiToolProfiles::SensitiveTools)
                            .json_binary()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(AiToolProfiles::IsActive)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(AiToolProfiles::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(ColumnDef::new(AiToolProfiles::CreatedBy).uuid().null())
                    .col(ColumnDef::new(AiToolProfiles::UpdatedBy).uuid().null())
                    .col(
                        ColumnDef::new(AiToolProfiles::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(AiToolProfiles::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiToolProfiles::Table, AiToolProfiles::TenantId)
                            .to(Alias::new("tenants"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_ai_tool_profiles_tenant_slug")
                    .table(AiToolProfiles::Table)
                    .unique()
                    .col(AiToolProfiles::TenantId)
                    .col(AiToolProfiles::Slug)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AiChatSessions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AiChatSessions::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(AiChatSessions::TenantId).uuid().not_null())
                    .col(
                        ColumnDef::new(AiChatSessions::Title)
                            .string_len(200)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiChatSessions::ProviderProfileId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(AiChatSessions::ToolProfileId).uuid().null())
                    .col(
                        ColumnDef::new(AiChatSessions::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(ColumnDef::new(AiChatSessions::CreatedBy).uuid().null())
                    .col(
                        ColumnDef::new(AiChatSessions::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(AiChatSessions::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(AiChatSessions::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiChatSessions::Table, AiChatSessions::TenantId)
                            .to(Alias::new("tenants"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiChatSessions::Table, AiChatSessions::ProviderProfileId)
                            .to(AiProviderProfiles::Table, AiProviderProfiles::Id)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiChatSessions::Table, AiChatSessions::ToolProfileId)
                            .to(AiToolProfiles::Table, AiToolProfiles::Id)
                            .on_delete(ForeignKeyAction::SetNull),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_ai_chat_sessions_tenant_updated")
                    .table(AiChatSessions::Table)
                    .col(AiChatSessions::TenantId)
                    .col(AiChatSessions::UpdatedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AiChatRuns::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AiChatRuns::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(AiChatRuns::TenantId).uuid().not_null())
                    .col(ColumnDef::new(AiChatRuns::SessionId).uuid().not_null())
                    .col(
                        ColumnDef::new(AiChatRuns::ProviderProfileId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(AiChatRuns::ToolProfileId).uuid().null())
                    .col(ColumnDef::new(AiChatRuns::Status).string_len(32).not_null())
                    .col(ColumnDef::new(AiChatRuns::Model).string_len(160).not_null())
                    .col(ColumnDef::new(AiChatRuns::Temperature).float().null())
                    .col(ColumnDef::new(AiChatRuns::MaxTokens).integer().null())
                    .col(ColumnDef::new(AiChatRuns::ErrorMessage).text().null())
                    .col(ColumnDef::new(AiChatRuns::PendingApprovalId).uuid().null())
                    .col(
                        ColumnDef::new(AiChatRuns::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(AiChatRuns::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(AiChatRuns::StartedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(AiChatRuns::CompletedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AiChatRuns::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiChatRuns::Table, AiChatRuns::TenantId)
                            .to(Alias::new("tenants"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiChatRuns::Table, AiChatRuns::SessionId)
                            .to(AiChatSessions::Table, AiChatSessions::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_ai_chat_runs_session_created")
                    .table(AiChatRuns::Table)
                    .col(AiChatRuns::SessionId)
                    .col(AiChatRuns::CreatedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AiChatMessages::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AiChatMessages::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(AiChatMessages::TenantId).uuid().not_null())
                    .col(ColumnDef::new(AiChatMessages::SessionId).uuid().not_null())
                    .col(ColumnDef::new(AiChatMessages::RunId).uuid().null())
                    .col(
                        ColumnDef::new(AiChatMessages::Role)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(ColumnDef::new(AiChatMessages::Content).text().null())
                    .col(ColumnDef::new(AiChatMessages::Name).string_len(128).null())
                    .col(
                        ColumnDef::new(AiChatMessages::ToolCallId)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AiChatMessages::ToolCalls)
                            .json_binary()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(AiChatMessages::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(ColumnDef::new(AiChatMessages::CreatedBy).uuid().null())
                    .col(
                        ColumnDef::new(AiChatMessages::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiChatMessages::Table, AiChatMessages::TenantId)
                            .to(Alias::new("tenants"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiChatMessages::Table, AiChatMessages::SessionId)
                            .to(AiChatSessions::Table, AiChatSessions::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiChatMessages::Table, AiChatMessages::RunId)
                            .to(AiChatRuns::Table, AiChatRuns::Id)
                            .on_delete(ForeignKeyAction::SetNull),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_ai_chat_messages_session_created")
                    .table(AiChatMessages::Table)
                    .col(AiChatMessages::SessionId)
                    .col(AiChatMessages::CreatedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AiApprovalRequests::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AiApprovalRequests::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AiApprovalRequests::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiApprovalRequests::SessionId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(AiApprovalRequests::RunId).uuid().not_null())
                    .col(
                        ColumnDef::new(AiApprovalRequests::ToolName)
                            .string_len(160)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiApprovalRequests::ToolCallId)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiApprovalRequests::ToolInput)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(ColumnDef::new(AiApprovalRequests::Reason).text().null())
                    .col(
                        ColumnDef::new(AiApprovalRequests::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(ColumnDef::new(AiApprovalRequests::ResolvedBy).uuid().null())
                    .col(
                        ColumnDef::new(AiApprovalRequests::ResolvedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AiApprovalRequests::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(AiApprovalRequests::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(AiApprovalRequests::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiApprovalRequests::Table, AiApprovalRequests::TenantId)
                            .to(Alias::new("tenants"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiApprovalRequests::Table, AiApprovalRequests::SessionId)
                            .to(AiChatSessions::Table, AiChatSessions::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiApprovalRequests::Table, AiApprovalRequests::RunId)
                            .to(AiChatRuns::Table, AiChatRuns::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_ai_approval_requests_run_status")
                    .table(AiApprovalRequests::Table)
                    .col(AiApprovalRequests::RunId)
                    .col(AiApprovalRequests::Status)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AiToolTraces::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AiToolTraces::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(AiToolTraces::TenantId).uuid().not_null())
                    .col(ColumnDef::new(AiToolTraces::SessionId).uuid().not_null())
                    .col(ColumnDef::new(AiToolTraces::RunId).uuid().not_null())
                    .col(
                        ColumnDef::new(AiToolTraces::ToolName)
                            .string_len(160)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiToolTraces::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AiToolTraces::InputPayload)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(AiToolTraces::OutputPayload)
                            .json_binary()
                            .null(),
                    )
                    .col(ColumnDef::new(AiToolTraces::ErrorMessage).text().null())
                    .col(
                        ColumnDef::new(AiToolTraces::DurationMs)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AiToolTraces::Sensitive)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(AiToolTraces::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(AiToolTraces::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiToolTraces::Table, AiToolTraces::TenantId)
                            .to(Alias::new("tenants"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiToolTraces::Table, AiToolTraces::SessionId)
                            .to(AiChatSessions::Table, AiChatSessions::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(AiToolTraces::Table, AiToolTraces::RunId)
                            .to(AiChatRuns::Table, AiChatRuns::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_ai_tool_traces_run_created")
                    .table(AiToolTraces::Table)
                    .col(AiToolTraces::RunId)
                    .col(AiToolTraces::CreatedAt)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(AiToolTraces::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(AiApprovalRequests::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(AiChatMessages::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(AiChatRuns::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(AiChatSessions::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(AiToolProfiles::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(AiProviderProfiles::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
enum AiProviderProfiles {
    Table,
    Id,
    TenantId,
    Slug,
    DisplayName,
    ProviderKind,
    BaseUrl,
    Model,
    ApiKeySecret,
    Temperature,
    MaxTokens,
    IsActive,
    Metadata,
    CreatedBy,
    UpdatedBy,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum AiToolProfiles {
    Table,
    Id,
    TenantId,
    Slug,
    DisplayName,
    Description,
    AllowedTools,
    DeniedTools,
    SensitiveTools,
    IsActive,
    Metadata,
    CreatedBy,
    UpdatedBy,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum AiChatSessions {
    Table,
    Id,
    TenantId,
    Title,
    ProviderProfileId,
    ToolProfileId,
    Status,
    CreatedBy,
    Metadata,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum AiChatRuns {
    Table,
    Id,
    TenantId,
    SessionId,
    ProviderProfileId,
    ToolProfileId,
    Status,
    Model,
    Temperature,
    MaxTokens,
    ErrorMessage,
    PendingApprovalId,
    Metadata,
    CreatedAt,
    StartedAt,
    CompletedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum AiChatMessages {
    Table,
    Id,
    TenantId,
    SessionId,
    RunId,
    Role,
    Content,
    Name,
    ToolCallId,
    ToolCalls,
    Metadata,
    CreatedBy,
    CreatedAt,
}

#[derive(DeriveIden)]
enum AiApprovalRequests {
    Table,
    Id,
    TenantId,
    SessionId,
    RunId,
    ToolName,
    ToolCallId,
    ToolInput,
    Reason,
    Status,
    ResolvedBy,
    ResolvedAt,
    Metadata,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum AiToolTraces {
    Table,
    Id,
    TenantId,
    SessionId,
    RunId,
    ToolName,
    Status,
    InputPayload,
    OutputPayload,
    ErrorMessage,
    DurationMs,
    Sensitive,
    CreatedAt,
    UpdatedAt,
}
