version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all-updates:
        update-types: ["major", "minor", "patch"]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-updates:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/apps/next-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-updates:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/apps/next-admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-updates:
        patterns: ["*"]
