use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(ModerationReports::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModerationReports::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::ScopeKind)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModerationReports::ScopeId).uuid())
                    .col(
                        ColumnDef::new(ModerationReports::SubjectModule)
                            .string_len(100)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::SubjectKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::SubjectId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::SubjectRevision)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::ReporterKind)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModerationReports::ReporterId).uuid())
                    .col(
                        ColumnDef::new(ModerationReports::ReasonCode)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModerationReports::DescriptionReference).string_len(500))
                    .col(
                        ColumnDef::new(ModerationReports::Status)
                            .string_len(32)
                            .not_null()
                            .default("submitted"),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::Metadata)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'{}'")),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(ModerationReports::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_moderation_reports_subject")
                    .table(ModerationReports::Table)
                    .col(ModerationReports::TenantId)
                    .col(ModerationReports::SubjectModule)
                    .col(ModerationReports::SubjectKind)
                    .col(ModerationReports::SubjectId)
                    .col(ModerationReports::SubjectRevision)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ModerationCases::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModerationCases::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ModerationCases::TenantId).uuid().not_null())
                    .col(
                        ColumnDef::new(ModerationCases::ScopeKind)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModerationCases::ScopeId).uuid())
                    .col(
                        ColumnDef::new(ModerationCases::SubjectModule)
                            .string_len(100)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationCases::SubjectKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModerationCases::SubjectId).uuid().not_null())
                    .col(
                        ColumnDef::new(ModerationCases::SubjectRevision)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationCases::QueueKey)
                            .string_len(100)
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModerationCases::PolicyId).uuid())
                    .col(
                        ColumnDef::new(ModerationCases::PolicyVersion)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationCases::Priority)
                            .string_len(32)
                            .not_null()
                            .default("normal"),
                    )
                    .col(
                        ColumnDef::new(ModerationCases::Status)
                            .string_len(32)
                            .not_null()
                            .default("open"),
                    )
                    .col(ColumnDef::new(ModerationCases::AssignedModeratorId).uuid())
                    .col(
                        ColumnDef::new(ModerationCases::Revision)
                            .big_integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(ModerationCases::Metadata)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'{}'")),
                    )
                    .col(
                        ColumnDef::new(ModerationCases::OpenedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(ColumnDef::new(ModerationCases::StartedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(ModerationCases::DecidedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(ModerationCases::ClosedAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(ModerationCases::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(ModerationCases::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_moderation_cases_queue")
                    .table(ModerationCases::Table)
                    .col(ModerationCases::TenantId)
                    .col(ModerationCases::QueueKey)
                    .col(ModerationCases::Status)
                    .col(ModerationCases::Priority)
                    .col(ModerationCases::OpenedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_moderation_cases_active_subject")
                    .table(ModerationCases::Table)
                    .col(ModerationCases::TenantId)
                    .col(ModerationCases::SubjectModule)
                    .col(ModerationCases::SubjectKind)
                    .col(ModerationCases::SubjectId)
                    .col(ModerationCases::SubjectRevision)
                    .col(ModerationCases::Status)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ModerationCaseReports::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModerationCaseReports::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationCaseReports::CaseId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationCaseReports::ReportId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationCaseReports::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_moderation_case_reports_case")
                            .from(ModerationCaseReports::Table, ModerationCaseReports::CaseId)
                            .to(ModerationCases::Table, ModerationCases::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_moderation_case_reports_report")
                            .from(
                                ModerationCaseReports::Table,
                                ModerationCaseReports::ReportId,
                            )
                            .to(ModerationReports::Table, ModerationReports::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_moderation_case_reports_unique")
                    .table(ModerationCaseReports::Table)
                    .col(ModerationCaseReports::TenantId)
                    .col(ModerationCaseReports::CaseId)
                    .col(ModerationCaseReports::ReportId)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ModerationDecisions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModerationDecisions::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::CaseId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::DecisionKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::ReasonCode)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::PolicySnapshot)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::SubjectRevision)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::DecisionHash)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::DecidedBy)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::DecidedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationDecisions::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_moderation_decisions_case")
                            .from(ModerationDecisions::Table, ModerationDecisions::CaseId)
                            .to(ModerationCases::Table, ModerationCases::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_moderation_decisions_case_hash")
                    .table(ModerationDecisions::Table)
                    .col(ModerationDecisions::TenantId)
                    .col(ModerationDecisions::CaseId)
                    .col(ModerationDecisions::DecisionHash)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ModerationReceipts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModerationReceipts::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModerationReceipts::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReceipts::OperationKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReceipts::IdempotencyKey)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReceipts::RequestHash)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationReceipts::Status)
                            .string_len(32)
                            .not_null()
                            .default("processing"),
                    )
                    .col(ColumnDef::new(ModerationReceipts::ResponseJson).json_binary())
                    .col(ColumnDef::new(ModerationReceipts::ErrorCode).string_len(120))
                    .col(
                        ColumnDef::new(ModerationReceipts::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(ModerationReceipts::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(ColumnDef::new(ModerationReceipts::CompletedAt).timestamp_with_time_zone())
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_moderation_receipts_identity")
                    .table(ModerationReceipts::Table)
                    .col(ModerationReceipts::TenantId)
                    .col(ModerationReceipts::OperationKind)
                    .col(ModerationReceipts::IdempotencyKey)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ModerationEvents::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModerationEvents::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ModerationEvents::TenantId).uuid().not_null())
                    .col(
                        ColumnDef::new(ModerationEvents::AggregateKind)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationEvents::AggregateId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationEvents::EventType)
                            .string_len(100)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationEvents::Payload)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationEvents::OccurredAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModerationEvents::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_moderation_events_aggregate")
                    .table(ModerationEvents::Table)
                    .col(ModerationEvents::TenantId)
                    .col(ModerationEvents::AggregateKind)
                    .col(ModerationEvents::AggregateId)
                    .col(ModerationEvents::OccurredAt)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(ModerationEvents::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModerationReceipts::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModerationDecisions::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModerationCaseReports::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModerationCases::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModerationReports::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
enum ModerationReports {
    Table,
    Id,
    TenantId,
    ScopeKind,
    ScopeId,
    SubjectModule,
    SubjectKind,
    SubjectId,
    SubjectRevision,
    ReporterKind,
    ReporterId,
    ReasonCode,
    DescriptionReference,
    Status,
    Metadata,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum ModerationCases {
    Table,
    Id,
    TenantId,
    ScopeKind,
    ScopeId,
    SubjectModule,
    SubjectKind,
    SubjectId,
    SubjectRevision,
    QueueKey,
    PolicyId,
    PolicyVersion,
    Priority,
    Status,
    AssignedModeratorId,
    Revision,
    Metadata,
    OpenedAt,
    StartedAt,
    DecidedAt,
    ClosedAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum ModerationCaseReports {
    Table,
    TenantId,
    CaseId,
    ReportId,
    CreatedAt,
}

#[derive(DeriveIden)]
enum ModerationDecisions {
    Table,
    Id,
    TenantId,
    CaseId,
    DecisionKind,
    ReasonCode,
    PolicySnapshot,
    SubjectRevision,
    DecisionHash,
    DecidedBy,
    DecidedAt,
    CreatedAt,
}

#[derive(DeriveIden)]
enum ModerationReceipts {
    Table,
    Id,
    TenantId,
    OperationKind,
    IdempotencyKey,
    RequestHash,
    Status,
    ResponseJson,
    ErrorCode,
    CreatedAt,
    UpdatedAt,
    CompletedAt,
}

#[derive(DeriveIden)]
enum ModerationEvents {
    Table,
    Id,
    TenantId,
    AggregateKind,
    AggregateId,
    EventType,
    Payload,
    OccurredAt,
    CreatedAt,
}
