use super::*;
use crate::model::*;
use rustok_core::RetentionPolicy;
use rustok_modules::{
    ArtifactReleaseRef, ModuleAuthoringBuildSubmission, ModuleBuildPublicationReceipt,
    ModuleBuildSignatureAuthority, ModuleCommandContext, OciArtifactReference,
};
use rustok_sandbox::{LocalSandboxScenarioComparison, LocalSandboxScenarioResult};
use sea_orm::Database;
use sea_orm_migration::prelude::SchemaManager;

async fn storage_with_script() -> (SeaOrmStorage, Uuid, Uuid, Script) {
    storage_with_script_parent(None).await
}

async fn storage_with_script_parent(
    parent_release: Option<ArtifactReleaseRef>,
) -> (SeaOrmStorage, Uuid, Uuid, Script) {
    let database = Database::connect("sqlite::memory:")
        .await
        .expect("sqlite memory database should connect");
    let manager = SchemaManager::new(&database);
    for migration in crate::migrations::migrations() {
        migration
            .up(&manager)
            .await
            .expect("Alloy migrations should apply");
    }
    let owner_tenant = Uuid::new_v4();
    let other_tenant = Uuid::new_v4();
    let storage = SeaOrmStorage::new(database);
    let mut script = Script::new(
        "tenant-only",
        RhaiWorkspace::single_source("40 + 2"),
        ScriptTrigger::Manual,
    );
    script.tenant_id = owner_tenant;
    script.parent_release = parent_release;
    let script = storage.save(script).await.expect("script should save");
    (storage, owner_tenant, other_tenant, script)
}

fn component_workspace() -> RustComponentWorkspace {
    let rendered = rustok_module_template::render(&rustok_module_template::ModuleTemplateInput {
        slug: "sample_module".to_string(),
        version: "1.1.0".to_string(),
        display_name: "Sample Module".to_string(),
    })
    .expect("rendered Component template");
    let mut files = rendered
        .files()
        .iter()
        .map(|file| crate::RustComponentSourceFile {
            path: file.path.to_string(),
            contents: String::from_utf8(file.contents.clone()).expect("UTF-8 template file"),
        })
        .collect::<Vec<_>>();
    files.push(crate::RustComponentSourceFile {
        path: "Cargo.lock".to_string(),
        contents: "# This file is automatically generated by Cargo.\nversion = 4\n".to_string(),
    });
    RustComponentWorkspace { files }
}

#[tokio::test]
async fn tenant_scoped_single_record_paths_hide_and_preserve_other_tenant_scripts() {
    let (storage, owner_tenant, other_tenant, script) = storage_with_script().await;
    let other = storage.for_tenant(other_tenant);

    assert!(matches!(
        other.get(script.id).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        other.save(script.clone()).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        other
            .delete(ScriptDeletionCommand {
                script_id: script.id,
                expected_revision: script.version,
                actor_id: "operator:delete".into(),
                reason: "The draft was intentionally removed.".into(),
                idempotency_key: Uuid::new_v4(),
            })
            .await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        other.set_status(script.id, ScriptStatus::Disabled).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        other.record_error(script.id).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        other.reset_errors(script.id).await,
        Err(ScriptError::NotFound { .. })
    ));

    let owner_script = storage
        .for_tenant(owner_tenant)
        .get(script.id)
        .await
        .expect("other tenant operations must not mutate the owner script");
    assert_eq!(owner_script.tenant_id, owner_tenant);
    assert_eq!(owner_script.status, ScriptStatus::Draft);
    assert_eq!(owner_script.error_count, 0);
}

#[tokio::test]
async fn component_candidate_persists_exact_parent_lineage_and_hides_cross_tenant_reads() {
    let parent_release = ArtifactReleaseRef {
        slug: "sample_module".to_string(),
        version: "1.0.0".to_string(),
        digest: format!("sha256:{}", "b".repeat(64)),
    };
    let (storage, owner_tenant, other_tenant, script) =
        storage_with_script_parent(Some(parent_release.clone())).await;
    let owner = storage.for_tenant(owner_tenant);
    owner
        .review(ReviewCommand {
            script_id: script.id,
            expected_revision: script.version,
            status: ReviewStatus::Approved,
            policy_revision: "policy:evolution".to_string(),
            actor_id: "operator:reviewer".to_string(),
            reason: None,
            idempotency_key: Uuid::new_v4(),
        })
        .await
        .expect("approved parent source");
    let command = RustComponentCandidateCommand {
        script_id: script.id,
        expected_revision: script.version,
        workspace: component_workspace(),
        actor_id: "operator:evolution".to_string(),
        idempotency_key: Uuid::new_v4(),
    };
    let candidate = owner
        .create_component_candidate(command.clone())
        .await
        .expect("durable Component candidate");
    assert_eq!(candidate.parent_release, parent_release);
    assert_eq!(candidate.parent_revision, script.version);
    assert_eq!(
        owner
            .create_component_candidate(command)
            .await
            .expect("exact candidate replay"),
        candidate
    );
    let review_command = RustComponentCandidateReviewCommand {
        candidate_id: candidate.id,
        status: ReviewStatus::Approved,
        policy_revision: "policy:component-review".to_string(),
        actor_id: "operator:component-reviewer".to_string(),
        reason: None,
        idempotency_key: Uuid::new_v4(),
    };
    let candidate_review = owner
        .review_component_candidate(review_command.clone())
        .await
        .expect("durable candidate approval");
    assert_eq!(candidate_review.source_digest, candidate.source_digest);
    assert_eq!(candidate_review.scenario_digest, candidate.scenario_digest);
    assert_eq!(
        owner
            .review_component_candidate(review_command)
            .await
            .expect("candidate review replay"),
        candidate_review
    );
    assert_eq!(
        owner
            .list_component_candidate_reviews(candidate.id)
            .await
            .expect("candidate review history"),
        vec![candidate_review]
    );
    let build_command = RustComponentCandidateBuildCommand {
        candidate_id: candidate.id,
        context: ModuleCommandContext {
            actor_id: Uuid::new_v4(),
            tenant_id: Some(owner_tenant),
            trace_id: "trace:component-build".to_string(),
            correlation_id: Uuid::new_v4(),
            idempotency_key: Uuid::new_v4(),
        },
        project_id: "alloy-component-candidate".to_string(),
        rust_toolchain: "1.90.0".to_string(),
        sdk_version: "0.1.0".to_string(),
        template_version: "0.1.0".to_string(),
        dependency_lock_digest: format!("sha256:{}", "d".repeat(64)),
    };
    let submission = ModuleAuthoringBuildSubmission {
        request_id: Uuid::new_v4(),
        build_created: true,
        source_created: true,
        source_reference: format!("cas://sha256:{}", "e".repeat(64)),
        source_digest: format!("sha256:{}", "e".repeat(64)),
        archive_bytes: 1024,
        source_bytes: 512,
        entries: 8,
    };
    let build =
        RustComponentCandidateBuild::from_submission(&candidate, &build_command, &submission)
            .expect("candidate build receipt");
    assert_eq!(
        owner
            .record_component_candidate_build(build.clone())
            .await
            .expect("durable build receipt"),
        build
    );
    assert_eq!(
        owner
            .record_component_candidate_build(build.clone())
            .await
            .expect("build receipt replay"),
        build
    );
    assert_eq!(
        owner
            .get_component_candidate_build(candidate.id, build.idempotency_key)
            .await
            .expect("candidate build read"),
        Some(build.clone())
    );
    let execution = crate::RustComponentCandidateBuildExecution {
        candidate_id: candidate.id,
        candidate_build_id: build.id,
        tenant_id: owner_tenant,
        candidate_source_digest: candidate.source_digest.clone(),
        scenario_digest: candidate.scenario_digest.clone(),
        archive_source_digest: build.archive_source_digest.clone(),
        build_request_id: build.build_request_id,
        source_reference: build.source_reference.clone(),
        build_result_revision: 3,
        component_digest: format!("sha256:{}", "f".repeat(64)),
        sbom_digest: format!("sha256:{}", "1".repeat(64)),
        provenance_digest: format!("sha256:{}", "2".repeat(64)),
        publication: ModuleBuildPublicationReceipt {
            artifact: OciArtifactReference {
                registry: "registry.example".to_string(),
                repository: "modules/sample-module".to_string(),
                digest: format!("sha256:{}", "3".repeat(64)),
            },
            signature_manifest: OciArtifactReference {
                registry: "registry.example".to_string(),
                repository: "modules/sample-module".to_string(),
                digest: format!("sha256:{}", "4".repeat(64)),
            },
            signature_authority: ModuleBuildSignatureAuthority::BuildService,
        },
        scenario_comparison: LocalSandboxScenarioComparison {
            scenario_digest: candidate.scenario_digest.clone(),
            result: LocalSandboxScenarioResult::Success,
        },
        created_at: Utc::now(),
    };
    assert_eq!(
        owner
            .record_component_candidate_build_execution(execution.clone())
            .await
            .expect("durable execution evidence"),
        execution
    );
    assert_eq!(
        owner
            .record_component_candidate_build_execution(execution.clone())
            .await
            .expect("execution evidence replay"),
        execution
    );
    assert_eq!(
        owner
            .get_component_candidate_build_execution(candidate.id, build.build_request_id)
            .await
            .expect("execution evidence read"),
        Some(execution.clone())
    );
    assert!(matches!(
        storage
            .for_tenant(other_tenant)
            .get_component_candidate(candidate.id)
            .await,
        Err(ScriptError::NotFound { .. })
    ));
    owner
        .delete(ScriptDeletionCommand {
            script_id: script.id,
            expected_revision: script.version,
            actor_id: "operator:delete".to_string(),
            reason: "The evolution draft was removed.".to_string(),
            idempotency_key: Uuid::new_v4(),
        })
        .await
        .expect("candidate owner deletion");
    draft_tombstone::Entity::update_many()
        .col_expr(
            draft_tombstone::Column::RetainUntil,
            Expr::value(Utc::now() - chrono::Duration::seconds(1)),
        )
        .filter(draft_tombstone::Column::Id.eq(script.id))
        .filter(draft_tombstone::Column::TenantId.eq(owner_tenant))
        .exec(&storage.db)
        .await
        .expect("candidate retention deadline");
    assert_eq!(
        storage
            .purge_expired_evidence(Utc::now(), 1)
            .await
            .expect("candidate evidence collection"),
        1
    );
    assert!(
        component_candidate::Entity::find_by_id(candidate.id)
            .one(&storage.db)
            .await
            .expect("candidate lookup after collection")
            .is_none()
    );
    assert!(
        component_candidate_review::Entity::find()
            .filter(component_candidate_review::Column::CandidateId.eq(candidate.id))
            .one(&storage.db)
            .await
            .expect("candidate review lookup after collection")
            .is_none()
    );
    assert!(
        component_candidate_build::Entity::find()
            .filter(component_candidate_build::Column::CandidateId.eq(candidate.id))
            .one(&storage.db)
            .await
            .expect("candidate build lookup after collection")
            .is_none()
    );
    assert!(
        component_candidate_build_execution::Entity::find()
            .filter(component_candidate_build_execution::Column::CandidateId.eq(candidate.id))
            .one(&storage.db)
            .await
            .expect("candidate build execution lookup after collection")
            .is_none()
    );
}

#[tokio::test]
async fn save_rejects_a_stale_revision_without_overwriting_the_current_script() {
    let (storage, owner_tenant, _, script) = storage_with_script().await;
    let owner = storage.for_tenant(owner_tenant);
    let stale = owner
        .get(script.id)
        .await
        .expect("stale script should load");
    let mut current = owner
        .get(script.id)
        .await
        .expect("current script should load");
    current.workspace = RhaiWorkspace::single_source("41 + 2");

    let updated = owner
        .save(current)
        .await
        .expect("current revision should save");

    assert_eq!(updated.version, 2);
    assert!(matches!(
        owner.save(stale).await,
        Err(ScriptError::RevisionConflict { expected: 1 })
    ));
    assert_eq!(
        owner
            .get(script.id)
            .await
            .expect("current script should remain available")
            .workspace
            .entrypoint_source()
            .expect("workspace source"),
        "41 + 2"
    );
}

#[tokio::test]
async fn save_persists_immutable_source_revision_lineage() {
    let (storage, owner_tenant, _, script) = storage_with_script().await;
    let owner = storage.for_tenant(owner_tenant);
    let mut next = owner
        .get(script.id)
        .await
        .expect("current script should load");
    next.workspace = RhaiWorkspace::single_source("41 + 2");
    next.author_id = Some("author:next".into());
    next.source_provenance = crate::SourceProvenance::remote_mcp("alloy_update_script");
    let saved = owner.save(next).await.expect("next revision should save");

    let revisions = owner
        .list_source_revisions(script.id)
        .await
        .expect("owner revision ledger should load");

    assert_eq!(saved.version, 2);
    assert_eq!(revisions.len(), 2);
    assert_eq!(revisions[0].revision, 1);
    assert_eq!(revisions[0].parent_revision, None);
    assert_eq!(
        revisions[0]
            .workspace
            .entrypoint_source()
            .expect("workspace source"),
        "40 + 2"
    );
    assert_eq!(revisions[1].revision, 2);
    assert_eq!(revisions[1].parent_revision, Some(1));
    assert_eq!(
        revisions[1]
            .workspace
            .entrypoint_source()
            .expect("workspace source"),
        "41 + 2"
    );
    assert_eq!(revisions[1].author_id.as_deref(), Some("author:next"));
    assert_eq!(
        revisions[1].source_provenance,
        crate::SourceProvenance::remote_mcp("alloy_update_script")
    );
    assert_eq!(
        revisions[1].source_digest,
        SeaOrmStorage::source_digest(&RhaiWorkspace::single_source("41 + 2"))
            .expect("workspace digest")
    );
}

#[tokio::test]
async fn source_revision_queries_are_tenant_scoped() {
    let (storage, owner_tenant, other_tenant, script) = storage_with_script().await;
    let owner = storage.for_tenant(owner_tenant);
    let other = storage.for_tenant(other_tenant);

    assert_eq!(
        owner
            .get_source_revision(script.id, 1)
            .await
            .expect("owner source revision should load")
            .workspace
            .entrypoint_source()
            .expect("workspace source"),
        "40 + 2"
    );
    assert!(matches!(
        other.get_source_revision(script.id, 1).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        other.list_source_revisions(script.id).await,
        Err(ScriptError::NotFound { .. })
    ));
}

#[tokio::test]
async fn legal_hold_is_durable_tenant_scoped_and_excluded_from_collection() {
    let (storage, owner_tenant, other_tenant, script) = storage_with_script().await;
    let owner = storage.for_tenant(owner_tenant);
    let other = storage.for_tenant(other_tenant);
    owner
        .delete(ScriptDeletionCommand {
            script_id: script.id,
            expected_revision: script.version,
            actor_id: "operator:retention".into(),
            reason: "The draft must be retained before a legal review.".into(),
            idempotency_key: Uuid::new_v4(),
        })
        .await
        .expect("deletion should create retained evidence");
    let initial = owner
        .get_deleted_evidence_retention(script.id)
        .await
        .expect("owner should read the source-free retention state");
    assert!(matches!(
        other.get_deleted_evidence_retention(script.id).await,
        Err(ScriptError::NotFound { .. })
    ));
    let hold = ScriptEvidenceRetentionCommand {
        script_id: script.id,
        deletion_request_digest: initial.deletion_request_digest.clone(),
        expected_retention_revision: initial.retention_revision,
        action: crate::ScriptEvidenceRetentionAction::ApplyLegalHold,
        actor_id: "operator:retention".into(),
        reason: "A legal investigation requires preservation.".into(),
        idempotency_key: Uuid::new_v4(),
    };
    let held = owner
        .update_deleted_evidence_retention(hold.clone())
        .await
        .expect("owner should place a legal hold");
    assert_eq!(held.policy, RetentionPolicy::LegalHold);
    assert_eq!(held.retain_until, None);
    assert_eq!(held.retention_revision, 2);
    let receipt = draft_retention_receipt::Entity::find()
        .filter(draft_retention_receipt::Column::ScriptId.eq(script.id))
        .filter(draft_retention_receipt::Column::TenantId.eq(owner_tenant))
        .one(&storage.db)
        .await
        .expect("retention receipt lookup should succeed")
        .expect("legal-hold receipt should persist");
    assert_eq!(receipt.action, "apply_legal_hold");
    assert_eq!(receipt.actor_id, "operator:retention");
    assert_eq!(
        receipt.deletion_request_digest,
        initial.deletion_request_digest
    );
    assert_eq!(
        receipt.retention_policy,
        RetentionPolicy::LegalHold.as_str()
    );
    assert_eq!(receipt.retain_until, None);
    assert_eq!(
        storage
            .purge_expired_evidence(Utc::now() + chrono::Duration::days(90), 8)
            .await
            .expect("legal-hold collection pass should succeed"),
        0
    );
    assert!(matches!(
        other.update_deleted_evidence_retention(hold.clone()).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert_eq!(
        owner
            .update_deleted_evidence_retention(hold.clone())
            .await
            .expect("exact hold retry should replay"),
        held
    );
    let mut conflicting_hold = hold;
    conflicting_hold.reason = "A different reason must not replay.".into();
    assert!(matches!(
        owner
            .update_deleted_evidence_retention(conflicting_hold)
            .await,
        Err(ScriptError::EvidenceRetention(
            ScriptEvidenceRetentionError::IdempotencyConflict
        ))
    ));

    let released = owner
        .update_deleted_evidence_retention(ScriptEvidenceRetentionCommand {
            script_id: script.id,
            deletion_request_digest: held.deletion_request_digest.clone(),
            expected_retention_revision: held.retention_revision,
            action: crate::ScriptEvidenceRetentionAction::ReleaseLegalHold,
            actor_id: "operator:retention".into(),
            reason: "The legal hold was released by its owner.".into(),
            idempotency_key: Uuid::new_v4(),
        })
        .await
        .expect("owner should release the legal hold");
    assert_eq!(released.policy, RetentionPolicy::RetainUntil);
    assert!(released.retain_until > Some(Utc::now()));
    assert_eq!(released.retention_revision, 3);
}

#[tokio::test]
async fn deleted_script_hides_retained_source_and_review_evidence() {
    let (storage, owner_tenant, _, script) = storage_with_script().await;
    let owner = storage.for_tenant(owner_tenant);
    let review_reason = "Review reason that must be erased after expiry.";
    let test_diagnostic = "Test diagnostic that must be erased after expiry.";
    let mut script = owner
        .get(script.id)
        .await
        .expect("current script should load");
    script.workspace.files.push(crate::RhaiWorkspaceFile {
        path: "tests/smoke.rhai".into(),
        kind: crate::RhaiWorkspaceFileKind::Test,
        contents: "true".into(),
    });
    let script = owner.save(script).await.expect("test revision should save");
    let review = ReviewCommand {
        script_id: script.id,
        expected_revision: script.version,
        status: ReviewStatus::ChangesRequested,
        policy_revision: "policy:current".into(),
        actor_id: "operator:reviewer".into(),
        reason: Some(review_reason.into()),
        idempotency_key: Uuid::new_v4(),
    };
    owner
        .review(review.clone())
        .await
        .expect("review should be recorded before deletion");
    let test = TestCommand {
        script_id: script.id,
        expected_revision: script.version,
        test_path: "tests/smoke.rhai".into(),
        actor_id: "operator:tester".into(),
        idempotency_key: Uuid::new_v4(),
    };
    let TestRunClaim::Claimed(lease) = owner
        .claim_test_run(test.clone())
        .await
        .expect("test claim should be recorded before deletion")
    else {
        panic!("new test command must claim a lease");
    };
    let terminal_test = TestCommand {
        script_id: script.id,
        expected_revision: script.version,
        test_path: "tests/smoke.rhai".into(),
        actor_id: "operator:tester".into(),
        idempotency_key: Uuid::new_v4(),
    };
    let TestRunClaim::Claimed(terminal_lease) = owner
        .claim_test_run(terminal_test)
        .await
        .expect("terminal test claim should be recorded before deletion")
    else {
        panic!("distinct test command must claim a lease");
    };
    owner
        .complete_test_run(
            terminal_lease.run.id,
            terminal_lease.lease_token,
            TestRunCompletion::failed(Some(test_diagnostic.into()))
                .expect("diagnostic should be valid test evidence"),
        )
        .await
        .expect("terminal diagnostic should persist until expiry");

    let deletion = ScriptDeletionCommand {
        script_id: script.id,
        expected_revision: script.version,
        actor_id: "operator:delete".into(),
        reason: "The draft was intentionally removed.".into(),
        idempotency_key: Uuid::new_v4(),
    };
    owner
        .delete(deletion.clone())
        .await
        .expect("current script should delete");
    let tombstone = owner
        .deletion_receipt(script.id)
        .await
        .expect("deletion receipt should load")
        .expect("deletion receipt should persist");
    assert_eq!(tombstone.deleted_by, deletion.actor_id);
    assert_eq!(tombstone.delete_reason, deletion.reason);
    assert_eq!(tombstone.idempotency_key, deletion.idempotency_key);
    assert_eq!(
        tombstone.retention_policy,
        RetentionPolicy::RetainUntil.as_str()
    );
    assert!(
        tombstone
            .retain_until
            .is_some_and(|retain_until| retain_until > tombstone.deleted_at)
    );
    owner
        .delete(deletion.clone())
        .await
        .expect("the exact deletion command should replay after removal");
    let mut conflicting_replay = deletion;
    conflicting_replay.reason = "A different retention reason.".into();
    assert!(matches!(
        owner.delete(conflicting_replay).await,
        Err(ScriptError::Deletion(
            ScriptDeletionError::IdempotencyConflict
        ))
    ));

    assert!(matches!(
        owner.get_source_revision(script.id, script.version).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        owner.list_source_revisions(script.id).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        owner.list_reviews(script.id, script.version).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        owner.review(review).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        owner.claim_test_run(test).await,
        Err(ScriptError::NotFound { .. })
    ));
    assert!(matches!(
        owner
            .complete_test_run(lease.run.id, lease.lease_token, TestRunCompletion::passed())
            .await,
        Err(ScriptError::NotFound { .. })
    ));
    let mut replacement = Script::new(
        "retired_id",
        RhaiWorkspace::single_source("41 + 2"),
        ScriptTrigger::Manual,
    );
    replacement.id = script.id;
    replacement.tenant_id = owner_tenant;
    assert!(matches!(
        owner.save(replacement).await,
        Err(ScriptError::InvalidLineage(_))
    ));

    let expired_at = Utc::now() - chrono::Duration::seconds(1);
    draft_tombstone::Entity::update_many()
        .col_expr(
            draft_tombstone::Column::RetainUntil,
            Expr::value(expired_at),
        )
        .filter(draft_tombstone::Column::Id.eq(script.id))
        .filter(draft_tombstone::Column::TenantId.eq(owner_tenant))
        .exec(&storage.db)
        .await
        .expect("retention expiry should be persisted for the reaper");
    assert_eq!(
        storage
            .purge_expired_evidence(Utc::now(), 8)
            .await
            .expect("global owner storage should collect expired evidence"),
        1
    );
    assert!(
        draft_tombstone::Entity::find_by_id(script.id)
            .one(&storage.db)
            .await
            .expect("tombstone lookup should succeed")
            .is_none()
    );
    assert!(
        draft_revision::Entity::find()
            .filter(draft_revision::Column::ScriptId.eq(script.id))
            .one(&storage.db)
            .await
            .expect("source revision lookup should succeed")
            .is_none()
    );
    assert!(
        draft_review::Entity::find()
            .filter(draft_review::Column::ScriptId.eq(script.id))
            .one(&storage.db)
            .await
            .expect("review lookup should succeed")
            .is_none()
    );
    assert!(
        draft_test_run::Entity::find()
            .filter(draft_test_run::Column::ScriptId.eq(script.id))
            .one(&storage.db)
            .await
            .expect("test-run lookup should succeed")
            .is_none()
    );
    let purge_receipt = draft_purge_receipt::Entity::find()
        .filter(draft_purge_receipt::Column::ScriptId.eq(script.id))
        .filter(draft_purge_receipt::Column::TenantId.eq(owner_tenant))
        .one(&storage.db)
        .await
        .expect("purge receipt lookup should succeed")
        .expect("content-free purge receipt should persist");
    assert_eq!(
        purge_receipt.retention_policy,
        RetentionPolicy::RetainUntil.as_str()
    );
    assert_eq!(purge_receipt.source_revision_count, 2);
    assert_eq!(purge_receipt.review_count, 1);
    assert_eq!(purge_receipt.test_run_count, 2);
    assert!(purge_receipt.deletion_request_digest.starts_with("sha256:"));
    let receipt_debug = format!("{purge_receipt:?}");
    assert!(!receipt_debug.contains(review_reason));
    assert!(!receipt_debug.contains(test_diagnostic));

    let mut replacement = Script::new(
        "reused_after_evidence_purge",
        RhaiWorkspace::single_source("43 + 2"),
        ScriptTrigger::Manual,
    );
    replacement.id = script.id;
    replacement.tenant_id = owner_tenant;
    owner
        .save(replacement)
        .await
        .expect("purged draft ID may be reused without retained evidence");
}
