use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(LedgerTransactions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(LedgerTransactions::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::SourceKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::SourceId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::OrderId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::CurrencyCode)
                            .string_len(3)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::DebitTotalAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::CreditTotalAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::PostedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(LedgerTransactions::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_marketplace_ledger_transaction_source")
                    .table(LedgerTransactions::Table)
                    .col(LedgerTransactions::TenantId)
                    .col(LedgerTransactions::SourceKind)
                    .col(LedgerTransactions::SourceId)
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_marketplace_ledger_transaction_order")
                    .table(LedgerTransactions::Table)
                    .col(LedgerTransactions::TenantId)
                    .col(LedgerTransactions::OrderId)
                    .col(LedgerTransactions::CreatedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(LedgerEntries::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(LedgerEntries::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(LedgerEntries::TenantId).uuid().not_null())
                    .col(
                        ColumnDef::new(LedgerEntries::TransactionId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(LedgerEntries::OrderId).uuid().not_null())
                    .col(
                        ColumnDef::new(LedgerEntries::AssessmentId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerEntries::AllocationId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerEntries::OrderLineItemId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(LedgerEntries::SellerId).uuid())
                    .col(
                        ColumnDef::new(LedgerEntries::AccountCode)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerEntries::Direction)
                            .string_len(16)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerEntries::CurrencyCode)
                            .string_len(3)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerEntries::Amount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerEntries::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(LedgerEntries::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        for index in [
            Index::create()
                .name("uq_marketplace_ledger_entry_assessment_account")
                .table(LedgerEntries::Table)
                .col(LedgerEntries::TenantId)
                .col(LedgerEntries::AssessmentId)
                .col(LedgerEntries::AccountCode)
                .unique()
                .to_owned(),
            Index::create()
                .name("idx_marketplace_ledger_entry_transaction")
                .table(LedgerEntries::Table)
                .col(LedgerEntries::TenantId)
                .col(LedgerEntries::TransactionId)
                .col(LedgerEntries::Id)
                .to_owned(),
            Index::create()
                .name("idx_marketplace_ledger_entry_seller_payable")
                .table(LedgerEntries::Table)
                .col(LedgerEntries::TenantId)
                .col(LedgerEntries::SellerId)
                .col(LedgerEntries::AccountCode)
                .col(LedgerEntries::CurrencyCode)
                .col(LedgerEntries::CreatedAt)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        manager
            .create_table(
                Table::create()
                    .table(LedgerReceipts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(LedgerReceipts::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(LedgerReceipts::TenantId).uuid().not_null())
                    .col(ColumnDef::new(LedgerReceipts::ActorId).uuid().not_null())
                    .col(
                        ColumnDef::new(LedgerReceipts::IdempotencyKey)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerReceipts::CommandKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerReceipts::RequestHash)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LedgerReceipts::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(ColumnDef::new(LedgerReceipts::ResponseJson).json_binary())
                    .col(
                        ColumnDef::new(LedgerReceipts::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(ColumnDef::new(LedgerReceipts::CompletedAt).timestamp_with_time_zone())
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_marketplace_ledger_receipt_key")
                    .table(LedgerReceipts::Table)
                    .col(LedgerReceipts::TenantId)
                    .col(LedgerReceipts::IdempotencyKey)
                    .unique()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(LedgerReceipts::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(LedgerEntries::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(LedgerTransactions::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
enum LedgerTransactions {
    Table,
    Id,
    TenantId,
    SourceKind,
    SourceId,
    OrderId,
    CurrencyCode,
    DebitTotalAmount,
    CreditTotalAmount,
    Status,
    PostedAt,
    Metadata,
    CreatedAt,
}

#[derive(Iden)]
enum LedgerEntries {
    Table,
    Id,
    TenantId,
    TransactionId,
    OrderId,
    AssessmentId,
    AllocationId,
    OrderLineItemId,
    SellerId,
    AccountCode,
    Direction,
    CurrencyCode,
    Amount,
    Metadata,
    CreatedAt,
}

#[derive(Iden)]
enum LedgerReceipts {
    Table,
    Id,
    TenantId,
    ActorId,
    IdempotencyKey,
    CommandKind,
    RequestHash,
    Status,
    ResponseJson,
    CreatedAt,
    CompletedAt,
}
