#[path = "../../rustok-build/src/module_manifest_contribution.rs"]
pub mod module_manifest_contribution;

use module_manifest_contribution::normalize_module_contribution_manifest;
use std::env;
use std::fs;
use std::path::PathBuf;

const MODULE_MANIFEST_RELATIVE_PATH: &str = "../rustok-module.toml";
const GENERATED_FILE: &str = "pages_contribution_manifest.rs";

fn main() {
    println!("cargo:rerun-if-changed={MODULE_MANIFEST_RELATIVE_PATH}");
    println!("cargo:rerun-if-changed=../../rustok-build/src/module_manifest_contribution.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let manifest_path = manifest_dir.join(MODULE_MANIFEST_RELATIVE_PATH);
    let source = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", manifest_path.display()));
    let normalized = normalize_module_contribution_manifest(&source)
        .unwrap_or_else(|error| panic!("invalid {} contribution metadata: {error}", manifest_path.display()))
        .unwrap_or_else(|| panic!("{} must declare fba.builder_consumer.contribution_manifest", manifest_path.display()));

    if normalized.module_id != "pages" {
        panic!(
            "Pages admin contribution generator requires module.slug='pages', got '{}'",
            normalized.module_id
        );
    }
    let cargo_version = env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION");
    if normalized.owner_version != cargo_version {
        panic!(
            "Pages module.version '{}' must match rustok-pages-admin package version '{cargo_version}'",
            normalized.owner_version
        );
    }

    let landing = normalized
        .role("landing_blocks")
        .unwrap_or_else(|| panic!("contribution_manifest must declare role='landing_blocks'"));
    let metadata = normalized
        .role("metadata")
        .unwrap_or_else(|| panic!("contribution_manifest must declare role='metadata'"));
    if landing.surface != "admin" || metadata.surface != "admin" {
        panic!("Pages landing_blocks and metadata contribution roles must remain on the admin surface");
    }
    if landing.provider == normalized.owner_provider {
        panic!("landing_blocks contribution must target a declared external provider");
    }
    if metadata.provider != normalized.owner_provider {
        panic!(
            "metadata contribution must target owner provider '{}'",
            normalized.owner_provider
        );
    }
    let fly_builtin_version = normalized
        .target_providers
        .get(&landing.provider)
        .unwrap_or_else(|| panic!("landing_blocks provider '{}' is not version-pinned", landing.provider));
    let metadata_property_editor_id = metadata
        .property_editor_id
        .as_deref()
        .unwrap_or_else(|| panic!("metadata contribution must declare exactly one property editor"));
    let metadata_component_type = metadata
        .property_editor_component_type
        .as_deref()
        .unwrap_or_else(|| panic!("metadata property editor must declare component_type"));
    let manifest_json = normalized
        .manifest_json()
        .expect("generated Pages contribution manifest must serialize");

    let mut generated = String::from(
        "// @generated by rustok-pages-admin/build.rs through rustok-build module metadata tooling from ../rustok-module.toml.\n// Do not edit by hand.\n\n",
    );
    push_str_const(&mut generated, "PAGES_MODULE_ID", &normalized.module_id);
    push_str_const(&mut generated, "PAGES_OWNER_PROVIDER", &normalized.owner_provider);
    push_str_const(&mut generated, "PAGES_OWNER_PROVIDER_VERSION", &normalized.owner_version);
    push_str_const(&mut generated, "FLY_BUILTIN_PROVIDER", &landing.provider);
    push_str_const(&mut generated, "FLY_BUILTIN_PROVIDER_VERSION", fly_builtin_version);
    push_str_const(&mut generated, "PAGES_LANDING_BLOCKS_CONTRIBUTION_ID", &landing.id);
    push_str_const(&mut generated, "PAGES_METADATA_CONTRIBUTION_ID", &metadata.id);
    push_str_const(&mut generated, "PAGES_METADATA_PROPERTY_EDITOR_ID", metadata_property_editor_id);
    push_str_const(&mut generated, "PAGES_METADATA_COMPONENT_TYPE", metadata_component_type);
    push_str_slice_const(&mut generated, "PAGES_BUILDER_CAPABILITIES", &normalized.builder_capabilities);
    push_str_slice_const(&mut generated, "PAGES_LANDING_BLOCK_CAPABILITIES", &landing.required_capabilities);
    push_str_slice_const(&mut generated, "PAGES_METADATA_CAPABILITIES", &metadata.required_capabilities);
    push_str_slice_const(&mut generated, "PAGES_LANDING_BLOCK_IDS", &landing.blocks);
    generated.push_str(&format!(
        "pub const GENERATED_PAGES_CONTRIBUTION_MANIFEST_JSON: &str = {manifest_json:?};\n"
    ));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join(GENERATED_FILE), generated)
        .expect("write generated Pages contribution manifest");
}

fn push_str_const(output: &mut String, name: &str, value: &str) {
    output.push_str(&format!("pub const {name}: &str = {value:?};\n"));
}

fn push_str_slice_const(output: &mut String, name: &str, values: &[String]) {
    output.push_str(&format!("pub const {name}: &[&str] = &["));
    for value in values {
        output.push_str(&format!("{value:?},"));
    }
    output.push_str("];\n");
}
