use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::controllers::categories::list_categories,
        crate::controllers::category_tree::get_category_tree,
        crate::controllers::categories::get_category,
        crate::controllers::categories::create_category,
        crate::controllers::categories::update_category,
        crate::controllers::categories::delete_category,
        crate::controllers::topics::list_topics,
        crate::controllers::topics::get_topic,
        crate::controllers::topics::create_topic,
        crate::controllers::topics::update_topic,
        crate::controllers::topics::delete_topic,
        crate::controllers::replies::list_replies,
        crate::controllers::replies::get_reply,
        crate::controllers::replies::create_reply,
        crate::controllers::replies::update_reply,
        crate::controllers::replies::delete_reply,
        crate::controllers::subscriptions::get_category_subscription_settings,
        crate::controllers::subscriptions::update_category_subscription_settings,
        crate::controllers::subscriptions::get_topic_subscription_settings,
        crate::controllers::subscriptions::update_topic_subscription_settings,
        crate::controllers::subscriptions::get_subscription_policy,
        crate::controllers::subscriptions::update_subscription_policy,
    ),
    components(
        schemas(
            crate::CreateCategoryInput,
            crate::UpdateCategoryInput,
            crate::CategoryResponse,
            crate::CategoryListItem,
            crate::CategoryTreeQuery,
            crate::CategoryBreadcrumb,
            crate::CategoryTreeNode,
            crate::CategoryTreeResponse,
            crate::CreateTopicInput,
            crate::UpdateTopicInput,
            crate::ListTopicsFilter,
            crate::TopicResponse,
            crate::TopicListItem,
            crate::CreateReplyInput,
            crate::UpdateReplyInput,
            crate::ListRepliesFilter,
            crate::ReplyResponse,
            crate::ReplyListItem,
            crate::CategoryCursorQuery,
            crate::TopicCursorQuery,
            crate::ReplyCursorQuery,
            crate::CategoryReadModel,
            crate::TopicReadModel,
            crate::ReplyReadModel,
            crate::CategoryCursorPage,
            crate::TopicCursorPage,
            crate::ReplyCursorPage,
            crate::ForumSubscriptionLevel,
            crate::ForumDigestMode,
            crate::ForumSubscriptionTargetType,
            crate::UpdateForumSubscriptionInput,
            crate::ForumSubscriptionResponse,
            crate::UpdateForumSubscriptionPolicyInput,
            crate::ForumSubscriptionPolicyResponse,
        )
    ),
    tags((name = "forum", description = "Forum endpoints"))
)]
pub struct ForumApiDoc;

pub fn openapi_document() -> utoipa::openapi::OpenApi {
    ForumApiDoc::openapi()
}
