use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

/// Platform resources.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Resource {
    Users,
    Tenants,
    Modules,
    Settings,
    FlexSchemas,
    FlexEntries,
    Products,
    Categories,
    Orders,
    Customers,
    Profiles,
    Groups,
    Regions,
    Payments,
    Fulfillments,
    Inventory,
    Discounts,
    MarketplaceSellers,
    MarketplaceListings,
    Posts,
    Pages,
    Nodes,
    Media,
    Seo,
    Comments,
    Tags,
    Taxonomy,
    Analytics,
    Logs,
    Webhooks,
    BlogPosts,
    BlogCategories,
    ForumCategories,
    ForumTopics,
    ForumReplies,
    Scripts,
    Mcp,
    AiProviders,
    AiTaskProfiles,
    AiSessions,
    AiRuns,
    AiApprovals,
    AiRouter,
    AiTextTasks,
    AiImageTasks,
    AiCodeTasks,
    AiAlloyTasks,
    AiMultimodalTasks,
    Workflows,
    WorkflowExecutions,
}

impl fmt::Display for Resource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let value = match self {
            Self::Users => "users",
            Self::Tenants => "tenants",
            Self::Modules => "modules",
            Self::Settings => "settings",
            Self::FlexSchemas => "flex_schemas",
            Self::FlexEntries => "flex_entries",
            Self::Products => "products",
            Self::Categories => "categories",
            Self::Orders => "orders",
            Self::Customers => "customers",
            Self::Profiles => "profiles",
            Self::Groups => "groups",
            Self::Regions => "regions",
            Self::Payments => "payments",
            Self::Fulfillments => "fulfillments",
            Self::Inventory => "inventory",
            Self::Discounts => "discounts",
            Self::MarketplaceSellers => "marketplace_sellers",
            Self::MarketplaceListings => "marketplace_listings",
            Self::Posts => "posts",
            Self::Pages => "pages",
            Self::Nodes => "nodes",
            Self::Media => "media",
            Self::Seo => "seo",
            Self::Comments => "comments",
            Self::Tags => "tags",
            Self::Taxonomy => "taxonomy",
            Self::Analytics => "analytics",
            Self::Logs => "logs",
            Self::Webhooks => "webhooks",
            Self::BlogPosts => "blog_posts",
            Self::BlogCategories => "blog_categories",
            Self::ForumCategories => "forum_categories",
            Self::ForumTopics => "forum_topics",
            Self::ForumReplies => "forum_replies",
            Self::Scripts => "scripts",
            Self::Mcp => "mcp",
            Self::AiProviders => "ai:providers",
            Self::AiTaskProfiles => "ai:task_profiles",
            Self::AiSessions => "ai:sessions",
            Self::AiRuns => "ai:runs",
            Self::AiApprovals => "ai:approvals",
            Self::AiRouter => "ai:router",
            Self::AiTextTasks => "ai:tasks:text",
            Self::AiImageTasks => "ai:tasks:image",
            Self::AiCodeTasks => "ai:tasks:code",
            Self::AiAlloyTasks => "ai:tasks:alloy",
            Self::AiMultimodalTasks => "ai:tasks:multimodal",
            Self::Workflows => "workflows",
            Self::WorkflowExecutions => "workflow_executions",
        };
        write!(f, "{value}")
    }
}

impl FromStr for Resource {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "users" => Ok(Self::Users),
            "tenants" => Ok(Self::Tenants),
            "modules" => Ok(Self::Modules),
            "settings" => Ok(Self::Settings),
            "flex_schemas" => Ok(Self::FlexSchemas),
            "flex_entries" => Ok(Self::FlexEntries),
            "products" => Ok(Self::Products),
            "categories" => Ok(Self::Categories),
            "orders" => Ok(Self::Orders),
            "customers" => Ok(Self::Customers),
            "profiles" => Ok(Self::Profiles),
            "groups" => Ok(Self::Groups),
            "regions" => Ok(Self::Regions),
            "payments" => Ok(Self::Payments),
            "fulfillments" => Ok(Self::Fulfillments),
            "inventory" => Ok(Self::Inventory),
            "discounts" => Ok(Self::Discounts),
            "marketplace_sellers" => Ok(Self::MarketplaceSellers),
            "marketplace_listings" => Ok(Self::MarketplaceListings),
            "posts" => Ok(Self::Posts),
            "pages" => Ok(Self::Pages),
            "nodes" => Ok(Self::Nodes),
            "media" => Ok(Self::Media),
            "seo" => Ok(Self::Seo),
            "comments" => Ok(Self::Comments),
            "tags" => Ok(Self::Tags),
            "taxonomy" => Ok(Self::Taxonomy),
            "analytics" => Ok(Self::Analytics),
            "logs" => Ok(Self::Logs),
            "webhooks" => Ok(Self::Webhooks),
            "blog_posts" => Ok(Self::BlogPosts),
            "blog_categories" => Ok(Self::BlogCategories),
            "forum_categories" => Ok(Self::ForumCategories),
            "forum_topics" => Ok(Self::ForumTopics),
            "forum_replies" => Ok(Self::ForumReplies),
            "scripts" => Ok(Self::Scripts),
            "mcp" => Ok(Self::Mcp),
            "ai:providers" => Ok(Self::AiProviders),
            "ai:task_profiles" => Ok(Self::AiTaskProfiles),
            "ai:sessions" => Ok(Self::AiSessions),
            "ai:runs" => Ok(Self::AiRuns),
            "ai:approvals" => Ok(Self::AiApprovals),
            "ai:router" => Ok(Self::AiRouter),
            "ai:tasks:text" => Ok(Self::AiTextTasks),
            "ai:tasks:image" => Ok(Self::AiImageTasks),
            "ai:tasks:code" => Ok(Self::AiCodeTasks),
            "ai:tasks:alloy" => Ok(Self::AiAlloyTasks),
            "ai:tasks:multimodal" => Ok(Self::AiMultimodalTasks),
            "workflows" => Ok(Self::Workflows),
            "workflow_executions" => Ok(Self::WorkflowExecutions),
            _ => Err(format!("Unknown resource: {value}")),
        }
    }
}

/// Actions over platform resources.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Action {
    Create,
    Read,
    Update,
    Delete,
    List,
    Export,
    Import,
    Manage,
    Publish,
    Moderate,
    Execute,
    Run,
    Cancel,
    Resolve,
    Override,
}

impl fmt::Display for Action {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let value = match self {
            Self::Create => "create",
            Self::Read => "read",
            Self::Update => "update",
            Self::Delete => "delete",
            Self::List => "list",
            Self::Export => "export",
            Self::Import => "import",
            Self::Manage => "manage",
            Self::Publish => "publish",
            Self::Moderate => "moderate",
            Self::Execute => "execute",
            Self::Run => "run",
            Self::Cancel => "cancel",
            Self::Resolve => "resolve",
            Self::Override => "override",
        };
        write!(f, "{value}")
    }
}

impl FromStr for Action {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "create" => Ok(Self::Create),
            "read" => Ok(Self::Read),
            "update" => Ok(Self::Update),
            "delete" => Ok(Self::Delete),
            "list" => Ok(Self::List),
            "export" => Ok(Self::Export),
            "import" => Ok(Self::Import),
            "manage" | "*" => Ok(Self::Manage),
            "publish" => Ok(Self::Publish),
            "moderate" => Ok(Self::Moderate),
            "execute" => Ok(Self::Execute),
            "run" => Ok(Self::Run),
            "cancel" => Ok(Self::Cancel),
            "resolve" => Ok(Self::Resolve),
            "override" => Ok(Self::Override),
            _ => Err(format!("Unknown action: {value}")),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Permission {
    pub resource: Resource,
    pub action: Action,
}

impl Permission {
    pub const fn new(resource: Resource, action: Action) -> Self {
        Self { resource, action }
    }
}

impl FromStr for Permission {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        let (resource, action) = value
            .rsplit_once(':')
            .ok_or_else(|| "Missing action".to_string())?;
        Ok(Self {
            resource: Resource::from_str(resource)?,
            action: Action::from_str(action)?,
        })
    }
}

impl fmt::Display for Permission {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}:{}", self.resource, self.action)
    }
}

macro_rules! permission_constants {
    ($( $name:ident => ($resource:ident, $action:ident) ),* $(,)?) => {
        $(pub const $name: Self = Self::new(Resource::$resource, Action::$action);)*
    };
}

impl Permission {
    permission_constants! {
        USERS_CREATE => (Users, Create),
        USERS_READ => (Users, Read),
        USERS_UPDATE => (Users, Update),
        USERS_DELETE => (Users, Delete),
        USERS_LIST => (Users, List),
        USERS_MANAGE => (Users, Manage),
        TENANTS_CREATE => (Tenants, Create),
        TENANTS_READ => (Tenants, Read),
        TENANTS_UPDATE => (Tenants, Update),
        TENANTS_DELETE => (Tenants, Delete),
        TENANTS_LIST => (Tenants, List),
        TENANTS_MANAGE => (Tenants, Manage),
        MODULES_READ => (Modules, Read),
        MODULES_LIST => (Modules, List),
        MODULES_MANAGE => (Modules, Manage),
        SETTINGS_LIST => (Settings, List),
        SETTINGS_READ => (Settings, Read),
        SETTINGS_UPDATE => (Settings, Update),
        SETTINGS_MANAGE => (Settings, Manage),
        PRODUCTS_CREATE => (Products, Create),
        PRODUCTS_READ => (Products, Read),
        PRODUCTS_UPDATE => (Products, Update),
        PRODUCTS_DELETE => (Products, Delete),
        PRODUCTS_LIST => (Products, List),
        PRODUCTS_MANAGE => (Products, Manage),
        ORDERS_CREATE => (Orders, Create),
        ORDERS_READ => (Orders, Read),
        ORDERS_UPDATE => (Orders, Update),
        ORDERS_DELETE => (Orders, Delete),
        ORDERS_LIST => (Orders, List),
        ORDERS_MANAGE => (Orders, Manage),
        CUSTOMERS_CREATE => (Customers, Create),
        CUSTOMERS_READ => (Customers, Read),
        CUSTOMERS_UPDATE => (Customers, Update),
        CUSTOMERS_DELETE => (Customers, Delete),
        CUSTOMERS_LIST => (Customers, List),
        CUSTOMERS_MANAGE => (Customers, Manage),
        PROFILES_CREATE => (Profiles, Create),
        PROFILES_READ => (Profiles, Read),
        PROFILES_UPDATE => (Profiles, Update),
        PROFILES_DELETE => (Profiles, Delete),
        PROFILES_LIST => (Profiles, List),
        PROFILES_MANAGE => (Profiles, Manage),
        GROUPS_CREATE => (Groups, Create),
        GROUPS_READ => (Groups, Read),
        GROUPS_UPDATE => (Groups, Update),
        GROUPS_DELETE => (Groups, Delete),
        GROUPS_LIST => (Groups, List),
        GROUPS_MODERATE => (Groups, Moderate),
        GROUPS_MANAGE => (Groups, Manage),
        REGIONS_CREATE => (Regions, Create),
        REGIONS_READ => (Regions, Read),
        REGIONS_UPDATE => (Regions, Update),
        REGIONS_DELETE => (Regions, Delete),
        REGIONS_LIST => (Regions, List),
        REGIONS_MANAGE => (Regions, Manage),
        TAXONOMY_CREATE => (Taxonomy, Create),
        TAXONOMY_READ => (Taxonomy, Read),
        TAXONOMY_UPDATE => (Taxonomy, Update),
        TAXONOMY_DELETE => (Taxonomy, Delete),
        TAXONOMY_LIST => (Taxonomy, List),
        TAXONOMY_MANAGE => (Taxonomy, Manage),
        PAYMENTS_CREATE => (Payments, Create),
        PAYMENTS_READ => (Payments, Read),
        PAYMENTS_UPDATE => (Payments, Update),
        PAYMENTS_DELETE => (Payments, Delete),
        PAYMENTS_LIST => (Payments, List),
        PAYMENTS_MANAGE => (Payments, Manage),
        FULFILLMENTS_CREATE => (Fulfillments, Create),
        FULFILLMENTS_READ => (Fulfillments, Read),
        FULFILLMENTS_UPDATE => (Fulfillments, Update),
        FULFILLMENTS_DELETE => (Fulfillments, Delete),
        FULFILLMENTS_LIST => (Fulfillments, List),
        FULFILLMENTS_MANAGE => (Fulfillments, Manage),
        MARKETPLACE_SELLERS_CREATE => (MarketplaceSellers, Create),
        MARKETPLACE_SELLERS_READ => (MarketplaceSellers, Read),
        MARKETPLACE_SELLERS_UPDATE => (MarketplaceSellers, Update),
        MARKETPLACE_SELLERS_DELETE => (MarketplaceSellers, Delete),
        MARKETPLACE_SELLERS_LIST => (MarketplaceSellers, List),
        MARKETPLACE_SELLERS_MANAGE => (MarketplaceSellers, Manage),
        MARKETPLACE_LISTINGS_CREATE => (MarketplaceListings, Create),
        MARKETPLACE_LISTINGS_READ => (MarketplaceListings, Read),
        MARKETPLACE_LISTINGS_UPDATE => (MarketplaceListings, Update),
        MARKETPLACE_LISTINGS_DELETE => (MarketplaceListings, Delete),
        MARKETPLACE_LISTINGS_LIST => (MarketplaceListings, List),
        MARKETPLACE_LISTINGS_MANAGE => (MarketplaceListings, Manage),
        MARKETPLACE_LISTINGS_PUBLISH => (MarketplaceListings, Publish),
        MARKETPLACE_LISTINGS_MODERATE => (MarketplaceListings, Moderate),
        POSTS_CREATE => (Posts, Create),
        POSTS_READ => (Posts, Read),
        POSTS_UPDATE => (Posts, Update),
        POSTS_DELETE => (Posts, Delete),
        POSTS_LIST => (Posts, List),
        POSTS_MANAGE => (Posts, Manage),
        NODES_CREATE => (Nodes, Create),
        NODES_READ => (Nodes, Read),
        NODES_UPDATE => (Nodes, Update),
        NODES_DELETE => (Nodes, Delete),
        NODES_LIST => (Nodes, List),
        NODES_MANAGE => (Nodes, Manage),
        PAGES_CREATE => (Pages, Create),
        PAGES_READ => (Pages, Read),
        PAGES_UPDATE => (Pages, Update),
        PAGES_DELETE => (Pages, Delete),
        PAGES_LIST => (Pages, List),
        PAGES_MANAGE => (Pages, Manage),
        SEO_READ => (Seo, Read),
        SEO_UPDATE => (Seo, Update),
        SEO_PUBLISH => (Seo, Publish),
        SEO_GENERATE => (Seo, Execute),
        SEO_MANAGE => (Seo, Manage),
        FLEX_SCHEMAS_CREATE => (FlexSchemas, Create),
        FLEX_SCHEMAS_READ => (FlexSchemas, Read),
        FLEX_SCHEMAS_UPDATE => (FlexSchemas, Update),
        FLEX_SCHEMAS_DELETE => (FlexSchemas, Delete),
        FLEX_SCHEMAS_LIST => (FlexSchemas, List),
        FLEX_SCHEMAS_MANAGE => (FlexSchemas, Manage),
        FLEX_ENTRIES_CREATE => (FlexEntries, Create),
        FLEX_ENTRIES_READ => (FlexEntries, Read),
        FLEX_ENTRIES_UPDATE => (FlexEntries, Update),
        FLEX_ENTRIES_DELETE => (FlexEntries, Delete),
        FLEX_ENTRIES_LIST => (FlexEntries, List),
        FLEX_ENTRIES_MANAGE => (FlexEntries, Manage),
        ANALYTICS_READ => (Analytics, Read),
        ANALYTICS_EXPORT => (Analytics, Export),
        LOGS_READ => (Logs, Read),
        LOGS_LIST => (Logs, List),
        BLOG_POSTS_CREATE => (BlogPosts, Create),
        BLOG_POSTS_READ => (BlogPosts, Read),
        BLOG_POSTS_UPDATE => (BlogPosts, Update),
        BLOG_POSTS_DELETE => (BlogPosts, Delete),
        BLOG_POSTS_LIST => (BlogPosts, List),
        BLOG_POSTS_PUBLISH => (BlogPosts, Publish),
        BLOG_POSTS_MANAGE => (BlogPosts, Manage),
        BLOG_CATEGORIES_CREATE => (BlogCategories, Create),
        BLOG_CATEGORIES_READ => (BlogCategories, Read),
        BLOG_CATEGORIES_UPDATE => (BlogCategories, Update),
        BLOG_CATEGORIES_DELETE => (BlogCategories, Delete),
        BLOG_CATEGORIES_LIST => (BlogCategories, List),
        BLOG_CATEGORIES_MANAGE => (BlogCategories, Manage),
        FORUM_CATEGORIES_CREATE => (ForumCategories, Create),
        FORUM_CATEGORIES_READ => (ForumCategories, Read),
        FORUM_CATEGORIES_UPDATE => (ForumCategories, Update),
        FORUM_CATEGORIES_DELETE => (ForumCategories, Delete),
        FORUM_CATEGORIES_LIST => (ForumCategories, List),
        FORUM_CATEGORIES_MANAGE => (ForumCategories, Manage),
        FORUM_TOPICS_CREATE => (ForumTopics, Create),
        FORUM_TOPICS_READ => (ForumTopics, Read),
        FORUM_TOPICS_UPDATE => (ForumTopics, Update),
        FORUM_TOPICS_DELETE => (ForumTopics, Delete),
        FORUM_TOPICS_LIST => (ForumTopics, List),
        FORUM_TOPICS_MODERATE => (ForumTopics, Moderate),
        FORUM_TOPICS_MANAGE => (ForumTopics, Manage),
        FORUM_REPLIES_CREATE => (ForumReplies, Create),
        FORUM_REPLIES_READ => (ForumReplies, Read),
        FORUM_REPLIES_UPDATE => (ForumReplies, Update),
        FORUM_REPLIES_DELETE => (ForumReplies, Delete),
        FORUM_REPLIES_LIST => (ForumReplies, List),
        FORUM_REPLIES_MODERATE => (ForumReplies, Moderate),
        FORUM_REPLIES_MANAGE => (ForumReplies, Manage),
        INVENTORY_CREATE => (Inventory, Create),
        INVENTORY_READ => (Inventory, Read),
        INVENTORY_UPDATE => (Inventory, Update),
        INVENTORY_DELETE => (Inventory, Delete),
        INVENTORY_LIST => (Inventory, List),
        INVENTORY_MANAGE => (Inventory, Manage),
        SCRIPTS_CREATE => (Scripts, Create),
        SCRIPTS_READ => (Scripts, Read),
        SCRIPTS_UPDATE => (Scripts, Update),
        SCRIPTS_DELETE => (Scripts, Delete),
        SCRIPTS_LIST => (Scripts, List),
        SCRIPTS_EXECUTE => (Scripts, Execute),
        SCRIPTS_MANAGE => (Scripts, Manage),
        MCP_CREATE => (Mcp, Create),
        MCP_READ => (Mcp, Read),
        MCP_UPDATE => (Mcp, Update),
        MCP_DELETE => (Mcp, Delete),
        MCP_LIST => (Mcp, List),
        MCP_MANAGE => (Mcp, Manage),
        AI_PROVIDERS_READ => (AiProviders, Read),
        AI_PROVIDERS_MANAGE => (AiProviders, Manage),
        AI_TASK_PROFILES_READ => (AiTaskProfiles, Read),
        AI_TASK_PROFILES_MANAGE => (AiTaskProfiles, Manage),
        AI_SESSIONS_READ => (AiSessions, Read),
        AI_SESSIONS_RUN => (AiSessions, Run),
        AI_RUNS_CANCEL => (AiRuns, Cancel),
        AI_APPROVALS_RESOLVE => (AiApprovals, Resolve),
        AI_ROUTER_OVERRIDE => (AiRouter, Override),
        AI_TASKS_TEXT_RUN => (AiTextTasks, Run),
        AI_TASKS_IMAGE_RUN => (AiImageTasks, Run),
        AI_TASKS_CODE_RUN => (AiCodeTasks, Run),
        AI_TASKS_ALLOY_RUN => (AiAlloyTasks, Run),
        AI_TASKS_MULTIMODAL_RUN => (AiMultimodalTasks, Run),
        WORKFLOWS_CREATE => (Workflows, Create),
        WORKFLOWS_READ => (Workflows, Read),
        WORKFLOWS_UPDATE => (Workflows, Update),
        WORKFLOWS_DELETE => (Workflows, Delete),
        WORKFLOWS_LIST => (Workflows, List),
        WORKFLOWS_EXECUTE => (Workflows, Execute),
        WORKFLOWS_MANAGE => (Workflows, Manage),
        WORKFLOW_EXECUTIONS_READ => (WorkflowExecutions, Read),
        WORKFLOW_EXECUTIONS_LIST => (WorkflowExecutions, List),
    }
}
