use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(PaymentProviderEvents::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(PaymentProviderEvents::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::ProviderId)
                            .string_len(100)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::DeliveryId)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::IdempotencyKey)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::PayloadHash)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::SignatureVerified)
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::Status)
                            .string_len(32)
                            .not_null()
                            .default("received"),
                    )
                    .col(ColumnDef::new(PaymentProviderEvents::EventType).string_len(191))
                    .col(
                        ColumnDef::new(PaymentProviderEvents::ExternalReference)
                            .string_len(191),
                    )
                    .col(ColumnDef::new(PaymentProviderEvents::EventMetadata).json_binary())
                    .col(
                        ColumnDef::new(PaymentProviderEvents::AttemptCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(PaymentProviderEvents::LeaseOwner).string_len(191))
                    .col(
                        ColumnDef::new(PaymentProviderEvents::LeaseExpiresAt)
                            .timestamp_with_time_zone(),
                    )
                    .col(ColumnDef::new(PaymentProviderEvents::ErrorCode).string_len(100))
                    .col(ColumnDef::new(PaymentProviderEvents::ErrorMessage).string_len(2000))
                    .col(
                        ColumnDef::new(PaymentProviderEvents::ReceivedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(PaymentProviderEvents::ProcessedAt)
                            .timestamp_with_time_zone(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("ux_payment_provider_events_delivery")
                    .table(PaymentProviderEvents::Table)
                    .col(PaymentProviderEvents::TenantId)
                    .col(PaymentProviderEvents::ProviderId)
                    .col(PaymentProviderEvents::DeliveryId)
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("ux_payment_provider_events_idempotency")
                    .table(PaymentProviderEvents::Table)
                    .col(PaymentProviderEvents::TenantId)
                    .col(PaymentProviderEvents::ProviderId)
                    .col(PaymentProviderEvents::IdempotencyKey)
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_payment_provider_events_recovery")
                    .table(PaymentProviderEvents::Table)
                    .col(PaymentProviderEvents::TenantId)
                    .col(PaymentProviderEvents::Status)
                    .col(PaymentProviderEvents::LeaseExpiresAt)
                    .col(PaymentProviderEvents::UpdatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_payment_provider_events_reference")
                    .table(PaymentProviderEvents::Table)
                    .col(PaymentProviderEvents::TenantId)
                    .col(PaymentProviderEvents::ProviderId)
                    .col(PaymentProviderEvents::ExternalReference)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(PaymentProviderEvents::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum PaymentProviderEvents {
    Table,
    Id,
    TenantId,
    ProviderId,
    DeliveryId,
    IdempotencyKey,
    PayloadHash,
    SignatureVerified,
    Status,
    EventType,
    ExternalReference,
    EventMetadata,
    AttemptCount,
    LeaseOwner,
    LeaseExpiresAt,
    ErrorCode,
    ErrorMessage,
    ReceivedAt,
    UpdatedAt,
    ProcessedAt,
}
