// @generated by scripts/generate/generate-cli-registry.mjs
// Do not edit by hand.

use rustok_cli_core::CommandProvider;

pub fn generated_providers() -> Vec<Box<dyn CommandProvider>> {
    vec![
        // core / core
        rustok_cli_platform::command_provider(),
    ]
}
