// @generated by scripts/generate/generate-cli-registry.mjs
// Do not edit by hand.

use rustok_cli_core::CommandProvider;
use rustok_runtime::RuntimeComposition;

pub fn generated_providers(runtime: &RuntimeComposition) -> Vec<Box<dyn CommandProvider>> {
    vec![
        // core / core
        rustok_cli_platform::command_provider(runtime),
        // media / media
        rustok_media_cli::command_provider(runtime),
    ]
}
