[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
ignore = ["./dist"]

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = ["scripts/tailwind-build.mjs"]

[[proxy]]
backend = "http://127.0.0.1:5150/api/"
rewrite = "/api/"

[[proxy]]
backend = "ws://127.0.0.1:5150/api/graphql/ws"
rewrite = "/api/graphql/ws"
ws = true
