// Auto-generated by next-fluent typegen. DO NOT EDIT DIRECTLY.
/* eslint-disable */

export type AppMessageKey =
  | 'Blog-comments-empty'
  | 'Blog.comments.empty'
  | 'Blog-comments-timeout'
  | 'Blog.comments.timeout'
  | 'Blog-comments-timeoutCached'
  | 'Blog.comments.timeoutCached'
  | 'Blog-comments-title'
  | 'Blog.comments.title'
  | 'Blog-comments-unavailable'
  | 'Blog.comments.unavailable'
  | 'Blog-comments-unavailableCached'
  | 'Blog.comments.unavailableCached'
  | 'Blog-latest-subtitle'
  | 'Blog.latest.subtitle'
  | 'Blog-latest-title'
  | 'Blog.latest.title'
  | 'Comments-composer-editorLabel'
  | 'Comments.composer.editorLabel'
  | 'Comments-composer-emptyError'
  | 'Comments.composer.emptyError'
  | 'Comments-composer-hint'
  | 'Comments.composer.hint'
  | 'Comments-composer-signInRequired'
  | 'Comments.composer.signInRequired'
  | 'Comments-composer-submit'
  | 'Comments.composer.submit'
  | 'Comments-composer-submitError'
  | 'Comments.composer.submitError'
  | 'Comments-composer-submitting'
  | 'Comments.composer.submitting'
  | 'Comments-composer-success'
  | 'Comments.composer.success'
  | 'Comments-composer-title'
  | 'Comments.composer.title'
  | 'richText-apply_link'
  | 'richText.apply_link'
  | 'richText-blockquote'
  | 'richText.blockquote'
  | 'richText-bold'
  | 'richText.bold'
  | 'richText-bullet_list'
  | 'richText.bullet_list'
  | 'richText-clear_formatting'
  | 'richText.clear_formatting'
  | 'richText-code'
  | 'richText.code'
  | 'richText-code_block'
  | 'richText.code_block'
  | 'richText-editor'
  | 'richText.editor'
  | 'richText-heading'
  | 'richText.heading'
  | 'richText-horizontal_rule'
  | 'richText.horizontal_rule'
  | 'richText-italic'
  | 'richText.italic'
  | 'richText-link'
  | 'richText.link'
  | 'richText-link_url'
  | 'richText.link_url'
  | 'richText-ordered_list'
  | 'richText.ordered_list'
  | 'richText-redo'
  | 'richText.redo'
  | 'richText-remove_link'
  | 'richText.remove_link'
  | 'richText-strike'
  | 'richText.strike'
  | 'richText-undo'
  | 'richText.undo'
  | 'Storefront-alertDescription'
  | 'Storefront.alertDescription'
  | 'Storefront-alertTitle'
  | 'Storefront.alertTitle'
  | 'Storefront-cards-flexDescription'
  | 'Storefront.cards.flexDescription'
  | 'Storefront-cards-flexTitle'
  | 'Storefront.cards.flexTitle'
  | 'Storefront-cards-launchDescription'
  | 'Storefront.cards.launchDescription'
  | 'Storefront-cards-launchTitle'
  | 'Storefront.cards.launchTitle'
  | 'Storefront-cards-stackTitle'
  | 'Storefront.cards.stackTitle'
  | 'Storefront-chips'
  | 'Storefront.chips'
  | 'Storefront-eyebrow'
  | 'Storefront.eyebrow'
  | 'Storefront-features'
  | 'Storefront.features'
  | 'Storefront-primaryCta'
  | 'Storefront.primaryCta'
  | 'Storefront-secondaryCta'
  | 'Storefront.secondaryCta'
  | 'Storefront-subtitle'
  | 'Storefront.subtitle'
  | 'Storefront-title'
  | 'Storefront.title';

export interface AppMessageArgs {
  'Blog.comments.empty'?: Record<string, never>;
  'Blog-comments-empty'?: Record<string, never>;
  'Blog.comments.timeout'?: Record<string, never>;
  'Blog-comments-timeout'?: Record<string, never>;
  'Blog.comments.timeoutCached'?: Record<string, never>;
  'Blog-comments-timeoutCached'?: Record<string, never>;
  'Blog.comments.title'?: Record<string, never>;
  'Blog-comments-title'?: Record<string, never>;
  'Blog.comments.unavailable'?: Record<string, never>;
  'Blog-comments-unavailable'?: Record<string, never>;
  'Blog.comments.unavailableCached'?: Record<string, never>;
  'Blog-comments-unavailableCached'?: Record<string, never>;
  'Blog.latest.subtitle'?: Record<string, never>;
  'Blog-latest-subtitle'?: Record<string, never>;
  'Blog.latest.title'?: Record<string, never>;
  'Blog-latest-title'?: Record<string, never>;
  'Comments.composer.editorLabel'?: Record<string, never>;
  'Comments-composer-editorLabel'?: Record<string, never>;
  'Comments.composer.emptyError'?: Record<string, never>;
  'Comments-composer-emptyError'?: Record<string, never>;
  'Comments.composer.hint'?: Record<string, never>;
  'Comments-composer-hint'?: Record<string, never>;
  'Comments.composer.signInRequired'?: Record<string, never>;
  'Comments-composer-signInRequired'?: Record<string, never>;
  'Comments.composer.submit'?: Record<string, never>;
  'Comments-composer-submit'?: Record<string, never>;
  'Comments.composer.submitError'?: Record<string, never>;
  'Comments-composer-submitError'?: Record<string, never>;
  'Comments.composer.submitting'?: Record<string, never>;
  'Comments-composer-submitting'?: Record<string, never>;
  'Comments.composer.success'?: Record<string, never>;
  'Comments-composer-success'?: Record<string, never>;
  'Comments.composer.title'?: Record<string, never>;
  'Comments-composer-title'?: Record<string, never>;
  'richText.apply_link'?: Record<string, never>;
  'richText-apply_link'?: Record<string, never>;
  'richText.blockquote'?: Record<string, never>;
  'richText-blockquote'?: Record<string, never>;
  'richText.bold'?: Record<string, never>;
  'richText-bold'?: Record<string, never>;
  'richText.bullet_list'?: Record<string, never>;
  'richText-bullet_list'?: Record<string, never>;
  'richText.clear_formatting'?: Record<string, never>;
  'richText-clear_formatting'?: Record<string, never>;
  'richText.code'?: Record<string, never>;
  'richText-code'?: Record<string, never>;
  'richText.code_block'?: Record<string, never>;
  'richText-code_block'?: Record<string, never>;
  'richText.editor'?: Record<string, never>;
  'richText-editor'?: Record<string, never>;
  'richText.heading'?: Record<string, never>;
  'richText-heading'?: Record<string, never>;
  'richText.horizontal_rule'?: Record<string, never>;
  'richText-horizontal_rule'?: Record<string, never>;
  'richText.italic'?: Record<string, never>;
  'richText-italic'?: Record<string, never>;
  'richText.link'?: Record<string, never>;
  'richText-link'?: Record<string, never>;
  'richText.link_url'?: Record<string, never>;
  'richText-link_url'?: Record<string, never>;
  'richText.ordered_list'?: Record<string, never>;
  'richText-ordered_list'?: Record<string, never>;
  'richText.redo'?: Record<string, never>;
  'richText-redo'?: Record<string, never>;
  'richText.remove_link'?: Record<string, never>;
  'richText-remove_link'?: Record<string, never>;
  'richText.strike'?: Record<string, never>;
  'richText-strike'?: Record<string, never>;
  'richText.undo'?: Record<string, never>;
  'richText-undo'?: Record<string, never>;
  'Storefront.alertDescription'?: Record<string, never>;
  'Storefront-alertDescription'?: Record<string, never>;
  'Storefront.alertTitle'?: Record<string, never>;
  'Storefront-alertTitle'?: Record<string, never>;
  'Storefront.cards.flexDescription'?: Record<string, never>;
  'Storefront-cards-flexDescription'?: Record<string, never>;
  'Storefront.cards.flexTitle'?: Record<string, never>;
  'Storefront-cards-flexTitle'?: Record<string, never>;
  'Storefront.cards.launchDescription'?: Record<string, never>;
  'Storefront-cards-launchDescription'?: Record<string, never>;
  'Storefront.cards.launchTitle'?: Record<string, never>;
  'Storefront-cards-launchTitle'?: Record<string, never>;
  'Storefront.cards.stackTitle'?: Record<string, never>;
  'Storefront-cards-stackTitle'?: Record<string, never>;
  'Storefront.chips'?: Record<string, never>;
  'Storefront-chips'?: Record<string, never>;
  'Storefront.eyebrow'?: Record<string, never>;
  'Storefront-eyebrow'?: Record<string, never>;
  'Storefront.features'?: Record<string, never>;
  'Storefront-features'?: Record<string, never>;
  'Storefront.primaryCta'?: Record<string, never>;
  'Storefront-primaryCta'?: Record<string, never>;
  'Storefront.secondaryCta'?: Record<string, never>;
  'Storefront-secondaryCta'?: Record<string, never>;
  'Storefront.subtitle'?: Record<string, never>;
  'Storefront-subtitle'?: Record<string, never>;
  'Storefront.title'?: Record<string, never>;
  'Storefront-title'?: Record<string, never>;
}
