// Auto-generated by next-fluent typegen. DO NOT EDIT DIRECTLY.
/* eslint-disable */

export type AppMessageKey =
  | 'Account-emptyOrders'
  | 'Account.emptyOrders'
  | 'Account-emptyOrdersDesc'
  | 'Account.emptyOrdersDesc'
  | 'Account-emptySearch'
  | 'Account.emptySearch'
  | 'Account-lookupEmptyError'
  | 'Account.lookupEmptyError'
  | 'Account-lookupPlaceholder'
  | 'Account.lookupPlaceholder'
  | 'Account-lookupSubmit'
  | 'Account.lookupSubmit'
  | 'Account-lookupSubtitle'
  | 'Account.lookupSubtitle'
  | 'Account-lookupTitle'
  | 'Account.lookupTitle'
  | 'Account-ordersSubtitle'
  | 'Account.ordersSubtitle'
  | 'Account-ordersTitle'
  | 'Account.ordersTitle'
  | 'Account-searchPlaceholder'
  | 'Account.searchPlaceholder'
  | 'Account-tabActive'
  | 'Account.tabActive'
  | 'Account-tabAll'
  | 'Account.tabAll'
  | 'Account-tabCancelled'
  | 'Account.tabCancelled'
  | 'Account-tabDelivered'
  | 'Account.tabDelivered'
  | 'Account-tabLookup'
  | 'Account.tabLookup'
  | 'Account-title'
  | 'Account.title'
  | 'Account-trackOrder'
  | 'Account.trackOrder'
  | 'Blog-comments-empty'
  | 'Blog.comments.empty'
  | 'Blog-comments-timeout'
  | 'Blog.comments.timeout'
  | 'Blog-comments-timeoutCached'
  | 'Blog.comments.timeoutCached'
  | 'Blog-comments-title'
  | 'Blog.comments.title'
  | 'Blog-comments-unavailable'
  | 'Blog.comments.unavailable'
  | 'Blog-comments-unavailableCached'
  | 'Blog.comments.unavailableCached'
  | 'Blog-latest-subtitle'
  | 'Blog.latest.subtitle'
  | 'Blog-latest-title'
  | 'Blog.latest.title'
  | 'Cart-browseCatalog'
  | 'Cart.browseCatalog'
  | 'Cart-calculatedAtCheckout'
  | 'Cart.calculatedAtCheckout'
  | 'Cart-continueShopping'
  | 'Cart.continueShopping'
  | 'Cart-currentlyEmpty'
  | 'Cart.currentlyEmpty'
  | 'Cart-discount'
  | 'Cart.discount'
  | 'Cart-empty'
  | 'Cart.empty'
  | 'Cart-emptySubtitle'
  | 'Cart.emptySubtitle'
  | 'Cart-itemsCount'
  | 'Cart.itemsCount'
  | 'Cart-loading'
  | 'Cart.loading'
  | 'Cart-open'
  | 'Cart.open'
  | 'Cart-proceedToCheckout'
  | 'Cart.proceedToCheckout'
  | 'Cart-remove'
  | 'Cart.remove'
  | 'Cart-shipping'
  | 'Cart.shipping'
  | 'Cart-subtotal'
  | 'Cart.subtotal'
  | 'Cart-title'
  | 'Cart.title'
  | 'Cart-total'
  | 'Cart.total'
  | 'Cart-unitPrice'
  | 'Cart.unitPrice'
  | 'Catalog-allCategories'
  | 'Catalog.allCategories'
  | 'Catalog-bundleBadge'
  | 'Catalog.bundleBadge'
  | 'Catalog-empty'
  | 'Catalog.empty'
  | 'Catalog-fromPrice'
  | 'Catalog.fromPrice'
  | 'Catalog-inStock'
  | 'Catalog.inStock'
  | 'Catalog-outOfStock'
  | 'Catalog.outOfStock'
  | 'Catalog-resetFilters'
  | 'Catalog.resetFilters'
  | 'Catalog-saleBadge'
  | 'Catalog.saleBadge'
  | 'Catalog-searchPlaceholder'
  | 'Catalog.searchPlaceholder'
  | 'Catalog-sortBy'
  | 'Catalog.sortBy'
  | 'Catalog-sortCreated'
  | 'Catalog.sortCreated'
  | 'Catalog-sortNewest'
  | 'Catalog.sortNewest'
  | 'Catalog-sortOldest'
  | 'Catalog.sortOldest'
  | 'Catalog-subtitle'
  | 'Catalog.subtitle'
  | 'Catalog-title'
  | 'Catalog.title'
  | 'Catalog-viewAll'
  | 'Catalog.viewAll'
  | 'Checkout-address'
  | 'Checkout.address'
  | 'Checkout-backToCatalog'
  | 'Checkout.backToCatalog'
  | 'Checkout-backToHome'
  | 'Checkout.backToHome'
  | 'Checkout-city'
  | 'Checkout.city'
  | 'Checkout-contactSection'
  | 'Checkout.contactSection'
  | 'Checkout-country'
  | 'Checkout.country'
  | 'Checkout-discount'
  | 'Checkout.discount'
  | 'Checkout-email'
  | 'Checkout.email'
  | 'Checkout-emptyCart'
  | 'Checkout.emptyCart'
  | 'Checkout-emptyCartSubtitle'
  | 'Checkout.emptyCartSubtitle'
  | 'Checkout-free'
  | 'Checkout.free'
  | 'Checkout-fullName'
  | 'Checkout.fullName'
  | 'Checkout-notes'
  | 'Checkout.notes'
  | 'Checkout-orderCustomer'
  | 'Checkout.orderCustomer'
  | 'Checkout-orderDestination'
  | 'Checkout.orderDestination'
  | 'Checkout-orderDetails'
  | 'Checkout.orderDetails'
  | 'Checkout-orderId'
  | 'Checkout.orderId'
  | 'Checkout-orderStatus'
  | 'Checkout.orderStatus'
  | 'Checkout-orderSummary'
  | 'Checkout.orderSummary'
  | 'Checkout-orderTotal'
  | 'Checkout.orderTotal'
  | 'Checkout-paymentCard'
  | 'Checkout.paymentCard'
  | 'Checkout-paymentCardDesc'
  | 'Checkout.paymentCardDesc'
  | 'Checkout-paymentCod'
  | 'Checkout.paymentCod'
  | 'Checkout-paymentCodDesc'
  | 'Checkout.paymentCodDesc'
  | 'Checkout-paymentSection'
  | 'Checkout.paymentSection'
  | 'Checkout-paymentTransfer'
  | 'Checkout.paymentTransfer'
  | 'Checkout-paymentTransferDesc'
  | 'Checkout.paymentTransferDesc'
  | 'Checkout-phone'
  | 'Checkout.phone'
  | 'Checkout-placeOrder'
  | 'Checkout.placeOrder'
  | 'Checkout-postalCode'
  | 'Checkout.postalCode'
  | 'Checkout-processing'
  | 'Checkout.processing'
  | 'Checkout-secure'
  | 'Checkout.secure'
  | 'Checkout-shipping'
  | 'Checkout.shipping'
  | 'Checkout-shippingMethod'
  | 'Checkout.shippingMethod'
  | 'Checkout-shippingSection'
  | 'Checkout.shippingSection'
  | 'Checkout-subtitle'
  | 'Checkout.subtitle'
  | 'Checkout-subtotal'
  | 'Checkout.subtotal'
  | 'Checkout-successBadge'
  | 'Checkout.successBadge'
  | 'Checkout-successTitle'
  | 'Checkout.successTitle'
  | 'Checkout-title'
  | 'Checkout.title'
  | 'Checkout-total'
  | 'Checkout.total'
  | 'Comments-composer-editorLabel'
  | 'Comments.composer.editorLabel'
  | 'Comments-composer-emptyError'
  | 'Comments.composer.emptyError'
  | 'Comments-composer-hint'
  | 'Comments.composer.hint'
  | 'Comments-composer-signInRequired'
  | 'Comments.composer.signInRequired'
  | 'Comments-composer-submit'
  | 'Comments.composer.submit'
  | 'Comments-composer-submitError'
  | 'Comments.composer.submitError'
  | 'Comments-composer-submitting'
  | 'Comments.composer.submitting'
  | 'Comments-composer-success'
  | 'Comments.composer.success'
  | 'Comments-composer-title'
  | 'Comments.composer.title'
  | 'Order-backToCatalog'
  | 'Order.backToCatalog'
  | 'Order-browseCatalog'
  | 'Order.browseCatalog'
  | 'Order-carrier'
  | 'Order.carrier'
  | 'Order-copied'
  | 'Order.copied'
  | 'Order-copy'
  | 'Order.copy'
  | 'Order-deliveryAddress'
  | 'Order.deliveryAddress'
  | 'Order-discount'
  | 'Order.discount'
  | 'Order-estimatedArrival'
  | 'Order.estimatedArrival'
  | 'Order-estimatedDays'
  | 'Order.estimatedDays'
  | 'Order-financialSummary'
  | 'Order.financialSummary'
  | 'Order-free'
  | 'Order.free'
  | 'Order-fulfillment'
  | 'Order.fulfillment'
  | 'Order-guaranteeQuality'
  | 'Order.guaranteeQuality'
  | 'Order-guaranteeReturn'
  | 'Order.guaranteeReturn'
  | 'Order-itemsCount'
  | 'Order.itemsCount'
  | 'Order-itemsTitle'
  | 'Order.itemsTitle'
  | 'Order-notFoundSubtitle'
  | 'Order.notFoundSubtitle'
  | 'Order-notFoundTitle'
  | 'Order.notFoundTitle'
  | 'Order-paid'
  | 'Order.paid'
  | 'Order-paymentMethod'
  | 'Order.paymentMethod'
  | 'Order-paymentStatus'
  | 'Order.paymentStatus'
  | 'Order-pending'
  | 'Order.pending'
  | 'Order-printReceipt'
  | 'Order.printReceipt'
  | 'Order-progressTitle'
  | 'Order.progressTitle'
  | 'Order-shipping'
  | 'Order.shipping'
  | 'Order-sku'
  | 'Order.sku'
  | 'Order-statusCancelled'
  | 'Order.statusCancelled'
  | 'Order-statusDelivered'
  | 'Order.statusDelivered'
  | 'Order-statusDeliveredDesc'
  | 'Order.statusDeliveredDesc'
  | 'Order-statusPaid'
  | 'Order.statusPaid'
  | 'Order-statusPaidDesc'
  | 'Order.statusPaidDesc'
  | 'Order-statusPlaced'
  | 'Order.statusPlaced'
  | 'Order-statusPlacedDesc'
  | 'Order.statusPlacedDesc'
  | 'Order-statusProcessing'
  | 'Order.statusProcessing'
  | 'Order-statusProcessingDesc'
  | 'Order.statusProcessingDesc'
  | 'Order-statusShipped'
  | 'Order.statusShipped'
  | 'Order-statusShippedDesc'
  | 'Order.statusShippedDesc'
  | 'Order-subtotal'
  | 'Order.subtotal'
  | 'Order-supportHint'
  | 'Order.supportHint'
  | 'Order-tax'
  | 'Order.tax'
  | 'Order-title'
  | 'Order.title'
  | 'Order-total'
  | 'Order.total'
  | 'Order-tracking'
  | 'Order.tracking'
  | 'Product-addedToCart'
  | 'Product.addedToCart'
  | 'Product-addToCart'
  | 'Product.addToCart'
  | 'Product-backToCatalog'
  | 'Product.backToCatalog'
  | 'Product-bundleIncludes'
  | 'Product.bundleIncludes'
  | 'Product-description'
  | 'Product.description'
  | 'Product-details'
  | 'Product.details'
  | 'Product-quantity'
  | 'Product.quantity'
  | 'Product-selectVariant'
  | 'Product.selectVariant'
  | 'Product-shipping'
  | 'Product.shipping'
  | 'Product-sku'
  | 'Product.sku'
  | 'Product-vendor'
  | 'Product.vendor'
  | 'richText-apply_link'
  | 'richText.apply_link'
  | 'richText-blockquote'
  | 'richText.blockquote'
  | 'richText-bold'
  | 'richText.bold'
  | 'richText-bullet_list'
  | 'richText.bullet_list'
  | 'richText-clear_formatting'
  | 'richText.clear_formatting'
  | 'richText-code'
  | 'richText.code'
  | 'richText-code_block'
  | 'richText.code_block'
  | 'richText-editor'
  | 'richText.editor'
  | 'richText-heading'
  | 'richText.heading'
  | 'richText-horizontal_rule'
  | 'richText.horizontal_rule'
  | 'richText-italic'
  | 'richText.italic'
  | 'richText-link'
  | 'richText.link'
  | 'richText-link_url'
  | 'richText.link_url'
  | 'richText-ordered_list'
  | 'richText.ordered_list'
  | 'richText-redo'
  | 'richText.redo'
  | 'richText-remove_link'
  | 'richText.remove_link'
  | 'richText-strike'
  | 'richText.strike'
  | 'richText-undo'
  | 'richText.undo'
  | 'Storefront-alertDescription'
  | 'Storefront.alertDescription'
  | 'Storefront-alertTitle'
  | 'Storefront.alertTitle'
  | 'Storefront-cards-flexDescription'
  | 'Storefront.cards.flexDescription'
  | 'Storefront-cards-flexTitle'
  | 'Storefront.cards.flexTitle'
  | 'Storefront-cards-launchDescription'
  | 'Storefront.cards.launchDescription'
  | 'Storefront-cards-launchTitle'
  | 'Storefront.cards.launchTitle'
  | 'Storefront-cards-stackTitle'
  | 'Storefront.cards.stackTitle'
  | 'Storefront-chips'
  | 'Storefront.chips'
  | 'Storefront-eyebrow'
  | 'Storefront.eyebrow'
  | 'Storefront-features'
  | 'Storefront.features'
  | 'Storefront-primaryCta'
  | 'Storefront.primaryCta'
  | 'Storefront-secondaryCta'
  | 'Storefront.secondaryCta'
  | 'Storefront-subtitle'
  | 'Storefront.subtitle'
  | 'Storefront-title'
  | 'Storefront.title';

export interface AppMessageArgs {
  'Account.emptyOrders'?: Record<string, never>;
  'Account-emptyOrders'?: Record<string, never>;
  'Account.emptyOrdersDesc'?: Record<string, never>;
  'Account-emptyOrdersDesc'?: Record<string, never>;
  'Account.emptySearch'?: Record<string, never>;
  'Account-emptySearch'?: Record<string, never>;
  'Account.lookupEmptyError'?: Record<string, never>;
  'Account-lookupEmptyError'?: Record<string, never>;
  'Account.lookupPlaceholder'?: Record<string, never>;
  'Account-lookupPlaceholder'?: Record<string, never>;
  'Account.lookupSubmit'?: Record<string, never>;
  'Account-lookupSubmit'?: Record<string, never>;
  'Account.lookupSubtitle'?: Record<string, never>;
  'Account-lookupSubtitle'?: Record<string, never>;
  'Account.lookupTitle'?: Record<string, never>;
  'Account-lookupTitle'?: Record<string, never>;
  'Account.ordersSubtitle'?: Record<string, never>;
  'Account-ordersSubtitle'?: Record<string, never>;
  'Account.ordersTitle'?: Record<string, never>;
  'Account-ordersTitle'?: Record<string, never>;
  'Account.searchPlaceholder'?: Record<string, never>;
  'Account-searchPlaceholder'?: Record<string, never>;
  'Account.tabActive'?: Record<string, never>;
  'Account-tabActive'?: Record<string, never>;
  'Account.tabAll'?: Record<string, never>;
  'Account-tabAll'?: Record<string, never>;
  'Account.tabCancelled'?: Record<string, never>;
  'Account-tabCancelled'?: Record<string, never>;
  'Account.tabDelivered'?: Record<string, never>;
  'Account-tabDelivered'?: Record<string, never>;
  'Account.tabLookup'?: Record<string, never>;
  'Account-tabLookup'?: Record<string, never>;
  'Account.title'?: Record<string, never>;
  'Account-title'?: Record<string, never>;
  'Account.trackOrder'?: Record<string, never>;
  'Account-trackOrder'?: Record<string, never>;
  'Blog.comments.empty'?: Record<string, never>;
  'Blog-comments-empty'?: Record<string, never>;
  'Blog.comments.timeout'?: Record<string, never>;
  'Blog-comments-timeout'?: Record<string, never>;
  'Blog.comments.timeoutCached'?: Record<string, never>;
  'Blog-comments-timeoutCached'?: Record<string, never>;
  'Blog.comments.title'?: Record<string, never>;
  'Blog-comments-title'?: Record<string, never>;
  'Blog.comments.unavailable'?: Record<string, never>;
  'Blog-comments-unavailable'?: Record<string, never>;
  'Blog.comments.unavailableCached'?: Record<string, never>;
  'Blog-comments-unavailableCached'?: Record<string, never>;
  'Blog.latest.subtitle'?: Record<string, never>;
  'Blog-latest-subtitle'?: Record<string, never>;
  'Blog.latest.title'?: Record<string, never>;
  'Blog-latest-title'?: Record<string, never>;
  'Cart.browseCatalog'?: Record<string, never>;
  'Cart-browseCatalog'?: Record<string, never>;
  'Cart.calculatedAtCheckout'?: Record<string, never>;
  'Cart-calculatedAtCheckout'?: Record<string, never>;
  'Cart.continueShopping'?: Record<string, never>;
  'Cart-continueShopping'?: Record<string, never>;
  'Cart.currentlyEmpty'?: Record<string, never>;
  'Cart-currentlyEmpty'?: Record<string, never>;
  'Cart.discount'?: Record<string, never>;
  'Cart-discount'?: Record<string, never>;
  'Cart.empty'?: Record<string, never>;
  'Cart-empty'?: Record<string, never>;
  'Cart.emptySubtitle'?: Record<string, never>;
  'Cart-emptySubtitle'?: Record<string, never>;
  'Cart.itemsCount': { 'count': string | number | Date };
  'Cart-itemsCount': { 'count': string | number | Date };
  'Cart.loading'?: Record<string, never>;
  'Cart-loading'?: Record<string, never>;
  'Cart.open'?: Record<string, never>;
  'Cart-open'?: Record<string, never>;
  'Cart.proceedToCheckout'?: Record<string, never>;
  'Cart-proceedToCheckout'?: Record<string, never>;
  'Cart.remove'?: Record<string, never>;
  'Cart-remove'?: Record<string, never>;
  'Cart.shipping'?: Record<string, never>;
  'Cart-shipping'?: Record<string, never>;
  'Cart.subtotal'?: Record<string, never>;
  'Cart-subtotal'?: Record<string, never>;
  'Cart.title'?: Record<string, never>;
  'Cart-title'?: Record<string, never>;
  'Cart.total'?: Record<string, never>;
  'Cart-total'?: Record<string, never>;
  'Cart.unitPrice'?: Record<string, never>;
  'Cart-unitPrice'?: Record<string, never>;
  'Catalog.allCategories'?: Record<string, never>;
  'Catalog-allCategories'?: Record<string, never>;
  'Catalog.bundleBadge'?: Record<string, never>;
  'Catalog-bundleBadge'?: Record<string, never>;
  'Catalog.empty'?: Record<string, never>;
  'Catalog-empty'?: Record<string, never>;
  'Catalog.fromPrice'?: Record<string, never>;
  'Catalog-fromPrice'?: Record<string, never>;
  'Catalog.inStock'?: Record<string, never>;
  'Catalog-inStock'?: Record<string, never>;
  'Catalog.outOfStock'?: Record<string, never>;
  'Catalog-outOfStock'?: Record<string, never>;
  'Catalog.resetFilters'?: Record<string, never>;
  'Catalog-resetFilters'?: Record<string, never>;
  'Catalog.saleBadge'?: Record<string, never>;
  'Catalog-saleBadge'?: Record<string, never>;
  'Catalog.searchPlaceholder'?: Record<string, never>;
  'Catalog-searchPlaceholder'?: Record<string, never>;
  'Catalog.sortBy'?: Record<string, never>;
  'Catalog-sortBy'?: Record<string, never>;
  'Catalog.sortCreated'?: Record<string, never>;
  'Catalog-sortCreated'?: Record<string, never>;
  'Catalog.sortNewest'?: Record<string, never>;
  'Catalog-sortNewest'?: Record<string, never>;
  'Catalog.sortOldest'?: Record<string, never>;
  'Catalog-sortOldest'?: Record<string, never>;
  'Catalog.subtitle'?: Record<string, never>;
  'Catalog-subtitle'?: Record<string, never>;
  'Catalog.title'?: Record<string, never>;
  'Catalog-title'?: Record<string, never>;
  'Catalog.viewAll'?: Record<string, never>;
  'Catalog-viewAll'?: Record<string, never>;
  'Checkout.address'?: Record<string, never>;
  'Checkout-address'?: Record<string, never>;
  'Checkout.backToCatalog'?: Record<string, never>;
  'Checkout-backToCatalog'?: Record<string, never>;
  'Checkout.backToHome'?: Record<string, never>;
  'Checkout-backToHome'?: Record<string, never>;
  'Checkout.city'?: Record<string, never>;
  'Checkout-city'?: Record<string, never>;
  'Checkout.contactSection'?: Record<string, never>;
  'Checkout-contactSection'?: Record<string, never>;
  'Checkout.country'?: Record<string, never>;
  'Checkout-country'?: Record<string, never>;
  'Checkout.discount'?: Record<string, never>;
  'Checkout-discount'?: Record<string, never>;
  'Checkout.email'?: Record<string, never>;
  'Checkout-email'?: Record<string, never>;
  'Checkout.emptyCart'?: Record<string, never>;
  'Checkout-emptyCart'?: Record<string, never>;
  'Checkout.emptyCartSubtitle'?: Record<string, never>;
  'Checkout-emptyCartSubtitle'?: Record<string, never>;
  'Checkout.free'?: Record<string, never>;
  'Checkout-free'?: Record<string, never>;
  'Checkout.fullName'?: Record<string, never>;
  'Checkout-fullName'?: Record<string, never>;
  'Checkout.notes'?: Record<string, never>;
  'Checkout-notes'?: Record<string, never>;
  'Checkout.orderCustomer'?: Record<string, never>;
  'Checkout-orderCustomer'?: Record<string, never>;
  'Checkout.orderDestination'?: Record<string, never>;
  'Checkout-orderDestination'?: Record<string, never>;
  'Checkout.orderDetails'?: Record<string, never>;
  'Checkout-orderDetails'?: Record<string, never>;
  'Checkout.orderId'?: Record<string, never>;
  'Checkout-orderId'?: Record<string, never>;
  'Checkout.orderStatus'?: Record<string, never>;
  'Checkout-orderStatus'?: Record<string, never>;
  'Checkout.orderSummary'?: Record<string, never>;
  'Checkout-orderSummary'?: Record<string, never>;
  'Checkout.orderTotal'?: Record<string, never>;
  'Checkout-orderTotal'?: Record<string, never>;
  'Checkout.paymentCard'?: Record<string, never>;
  'Checkout-paymentCard'?: Record<string, never>;
  'Checkout.paymentCardDesc'?: Record<string, never>;
  'Checkout-paymentCardDesc'?: Record<string, never>;
  'Checkout.paymentCod'?: Record<string, never>;
  'Checkout-paymentCod'?: Record<string, never>;
  'Checkout.paymentCodDesc'?: Record<string, never>;
  'Checkout-paymentCodDesc'?: Record<string, never>;
  'Checkout.paymentSection'?: Record<string, never>;
  'Checkout-paymentSection'?: Record<string, never>;
  'Checkout.paymentTransfer'?: Record<string, never>;
  'Checkout-paymentTransfer'?: Record<string, never>;
  'Checkout.paymentTransferDesc'?: Record<string, never>;
  'Checkout-paymentTransferDesc'?: Record<string, never>;
  'Checkout.phone'?: Record<string, never>;
  'Checkout-phone'?: Record<string, never>;
  'Checkout.placeOrder'?: Record<string, never>;
  'Checkout-placeOrder'?: Record<string, never>;
  'Checkout.postalCode'?: Record<string, never>;
  'Checkout-postalCode'?: Record<string, never>;
  'Checkout.processing'?: Record<string, never>;
  'Checkout-processing'?: Record<string, never>;
  'Checkout.secure'?: Record<string, never>;
  'Checkout-secure'?: Record<string, never>;
  'Checkout.shipping'?: Record<string, never>;
  'Checkout-shipping'?: Record<string, never>;
  'Checkout.shippingMethod'?: Record<string, never>;
  'Checkout-shippingMethod'?: Record<string, never>;
  'Checkout.shippingSection'?: Record<string, never>;
  'Checkout-shippingSection'?: Record<string, never>;
  'Checkout.subtitle'?: Record<string, never>;
  'Checkout-subtitle'?: Record<string, never>;
  'Checkout.subtotal'?: Record<string, never>;
  'Checkout-subtotal'?: Record<string, never>;
  'Checkout.successBadge'?: Record<string, never>;
  'Checkout-successBadge'?: Record<string, never>;
  'Checkout.successTitle'?: Record<string, never>;
  'Checkout-successTitle'?: Record<string, never>;
  'Checkout.title'?: Record<string, never>;
  'Checkout-title'?: Record<string, never>;
  'Checkout.total'?: Record<string, never>;
  'Checkout-total'?: Record<string, never>;
  'Comments.composer.editorLabel'?: Record<string, never>;
  'Comments-composer-editorLabel'?: Record<string, never>;
  'Comments.composer.emptyError'?: Record<string, never>;
  'Comments-composer-emptyError'?: Record<string, never>;
  'Comments.composer.hint'?: Record<string, never>;
  'Comments-composer-hint'?: Record<string, never>;
  'Comments.composer.signInRequired'?: Record<string, never>;
  'Comments-composer-signInRequired'?: Record<string, never>;
  'Comments.composer.submit'?: Record<string, never>;
  'Comments-composer-submit'?: Record<string, never>;
  'Comments.composer.submitError'?: Record<string, never>;
  'Comments-composer-submitError'?: Record<string, never>;
  'Comments.composer.submitting'?: Record<string, never>;
  'Comments-composer-submitting'?: Record<string, never>;
  'Comments.composer.success'?: Record<string, never>;
  'Comments-composer-success'?: Record<string, never>;
  'Comments.composer.title'?: Record<string, never>;
  'Comments-composer-title'?: Record<string, never>;
  'Order.backToCatalog'?: Record<string, never>;
  'Order-backToCatalog'?: Record<string, never>;
  'Order.browseCatalog'?: Record<string, never>;
  'Order-browseCatalog'?: Record<string, never>;
  'Order.carrier'?: Record<string, never>;
  'Order-carrier'?: Record<string, never>;
  'Order.copied'?: Record<string, never>;
  'Order-copied'?: Record<string, never>;
  'Order.copy'?: Record<string, never>;
  'Order-copy'?: Record<string, never>;
  'Order.deliveryAddress'?: Record<string, never>;
  'Order-deliveryAddress'?: Record<string, never>;
  'Order.discount'?: Record<string, never>;
  'Order-discount'?: Record<string, never>;
  'Order.estimatedArrival'?: Record<string, never>;
  'Order-estimatedArrival'?: Record<string, never>;
  'Order.estimatedDays'?: Record<string, never>;
  'Order-estimatedDays'?: Record<string, never>;
  'Order.financialSummary'?: Record<string, never>;
  'Order-financialSummary'?: Record<string, never>;
  'Order.free'?: Record<string, never>;
  'Order-free'?: Record<string, never>;
  'Order.fulfillment'?: Record<string, never>;
  'Order-fulfillment'?: Record<string, never>;
  'Order.guaranteeQuality'?: Record<string, never>;
  'Order-guaranteeQuality'?: Record<string, never>;
  'Order.guaranteeReturn'?: Record<string, never>;
  'Order-guaranteeReturn'?: Record<string, never>;
  'Order.itemsCount': { 'count': string | number | Date };
  'Order-itemsCount': { 'count': string | number | Date };
  'Order.itemsTitle'?: Record<string, never>;
  'Order-itemsTitle'?: Record<string, never>;
  'Order.notFoundSubtitle': { 'id': string | number | Date };
  'Order-notFoundSubtitle': { 'id': string | number | Date };
  'Order.notFoundTitle'?: Record<string, never>;
  'Order-notFoundTitle'?: Record<string, never>;
  'Order.paid'?: Record<string, never>;
  'Order-paid'?: Record<string, never>;
  'Order.paymentMethod'?: Record<string, never>;
  'Order-paymentMethod'?: Record<string, never>;
  'Order.paymentStatus'?: Record<string, never>;
  'Order-paymentStatus'?: Record<string, never>;
  'Order.pending'?: Record<string, never>;
  'Order-pending'?: Record<string, never>;
  'Order.printReceipt'?: Record<string, never>;
  'Order-printReceipt'?: Record<string, never>;
  'Order.progressTitle'?: Record<string, never>;
  'Order-progressTitle'?: Record<string, never>;
  'Order.shipping'?: Record<string, never>;
  'Order-shipping'?: Record<string, never>;
  'Order.sku'?: Record<string, never>;
  'Order-sku'?: Record<string, never>;
  'Order.statusCancelled'?: Record<string, never>;
  'Order-statusCancelled'?: Record<string, never>;
  'Order.statusDelivered'?: Record<string, never>;
  'Order-statusDelivered'?: Record<string, never>;
  'Order.statusDeliveredDesc'?: Record<string, never>;
  'Order-statusDeliveredDesc'?: Record<string, never>;
  'Order.statusPaid'?: Record<string, never>;
  'Order-statusPaid'?: Record<string, never>;
  'Order.statusPaidDesc'?: Record<string, never>;
  'Order-statusPaidDesc'?: Record<string, never>;
  'Order.statusPlaced'?: Record<string, never>;
  'Order-statusPlaced'?: Record<string, never>;
  'Order.statusPlacedDesc'?: Record<string, never>;
  'Order-statusPlacedDesc'?: Record<string, never>;
  'Order.statusProcessing'?: Record<string, never>;
  'Order-statusProcessing'?: Record<string, never>;
  'Order.statusProcessingDesc'?: Record<string, never>;
  'Order-statusProcessingDesc'?: Record<string, never>;
  'Order.statusShipped'?: Record<string, never>;
  'Order-statusShipped'?: Record<string, never>;
  'Order.statusShippedDesc'?: Record<string, never>;
  'Order-statusShippedDesc'?: Record<string, never>;
  'Order.subtotal'?: Record<string, never>;
  'Order-subtotal'?: Record<string, never>;
  'Order.supportHint'?: Record<string, never>;
  'Order-supportHint'?: Record<string, never>;
  'Order.tax'?: Record<string, never>;
  'Order-tax'?: Record<string, never>;
  'Order.title': { 'id': string | number | Date };
  'Order-title': { 'id': string | number | Date };
  'Order.total'?: Record<string, never>;
  'Order-total'?: Record<string, never>;
  'Order.tracking'?: Record<string, never>;
  'Order-tracking'?: Record<string, never>;
  'Product.addedToCart'?: Record<string, never>;
  'Product-addedToCart'?: Record<string, never>;
  'Product.addToCart'?: Record<string, never>;
  'Product-addToCart'?: Record<string, never>;
  'Product.backToCatalog'?: Record<string, never>;
  'Product-backToCatalog'?: Record<string, never>;
  'Product.bundleIncludes'?: Record<string, never>;
  'Product-bundleIncludes'?: Record<string, never>;
  'Product.description'?: Record<string, never>;
  'Product-description'?: Record<string, never>;
  'Product.details'?: Record<string, never>;
  'Product-details'?: Record<string, never>;
  'Product.quantity'?: Record<string, never>;
  'Product-quantity'?: Record<string, never>;
  'Product.selectVariant'?: Record<string, never>;
  'Product-selectVariant'?: Record<string, never>;
  'Product.shipping'?: Record<string, never>;
  'Product-shipping'?: Record<string, never>;
  'Product.sku'?: Record<string, never>;
  'Product-sku'?: Record<string, never>;
  'Product.vendor'?: Record<string, never>;
  'Product-vendor'?: Record<string, never>;
  'richText.apply_link'?: Record<string, never>;
  'richText-apply_link'?: Record<string, never>;
  'richText.blockquote'?: Record<string, never>;
  'richText-blockquote'?: Record<string, never>;
  'richText.bold'?: Record<string, never>;
  'richText-bold'?: Record<string, never>;
  'richText.bullet_list'?: Record<string, never>;
  'richText-bullet_list'?: Record<string, never>;
  'richText.clear_formatting'?: Record<string, never>;
  'richText-clear_formatting'?: Record<string, never>;
  'richText.code'?: Record<string, never>;
  'richText-code'?: Record<string, never>;
  'richText.code_block'?: Record<string, never>;
  'richText-code_block'?: Record<string, never>;
  'richText.editor'?: Record<string, never>;
  'richText-editor'?: Record<string, never>;
  'richText.heading'?: Record<string, never>;
  'richText-heading'?: Record<string, never>;
  'richText.horizontal_rule'?: Record<string, never>;
  'richText-horizontal_rule'?: Record<string, never>;
  'richText.italic'?: Record<string, never>;
  'richText-italic'?: Record<string, never>;
  'richText.link'?: Record<string, never>;
  'richText-link'?: Record<string, never>;
  'richText.link_url'?: Record<string, never>;
  'richText-link_url'?: Record<string, never>;
  'richText.ordered_list'?: Record<string, never>;
  'richText-ordered_list'?: Record<string, never>;
  'richText.redo'?: Record<string, never>;
  'richText-redo'?: Record<string, never>;
  'richText.remove_link'?: Record<string, never>;
  'richText-remove_link'?: Record<string, never>;
  'richText.strike'?: Record<string, never>;
  'richText-strike'?: Record<string, never>;
  'richText.undo'?: Record<string, never>;
  'richText-undo'?: Record<string, never>;
  'Storefront.alertDescription'?: Record<string, never>;
  'Storefront-alertDescription'?: Record<string, never>;
  'Storefront.alertTitle'?: Record<string, never>;
  'Storefront-alertTitle'?: Record<string, never>;
  'Storefront.cards.flexDescription'?: Record<string, never>;
  'Storefront-cards-flexDescription'?: Record<string, never>;
  'Storefront.cards.flexTitle'?: Record<string, never>;
  'Storefront-cards-flexTitle'?: Record<string, never>;
  'Storefront.cards.launchDescription'?: Record<string, never>;
  'Storefront-cards-launchDescription'?: Record<string, never>;
  'Storefront.cards.launchTitle'?: Record<string, never>;
  'Storefront-cards-launchTitle'?: Record<string, never>;
  'Storefront.cards.stackTitle'?: Record<string, never>;
  'Storefront-cards-stackTitle'?: Record<string, never>;
  'Storefront.chips'?: Record<string, never>;
  'Storefront-chips'?: Record<string, never>;
  'Storefront.eyebrow'?: Record<string, never>;
  'Storefront-eyebrow'?: Record<string, never>;
  'Storefront.features'?: Record<string, never>;
  'Storefront-features'?: Record<string, never>;
  'Storefront.primaryCta'?: Record<string, never>;
  'Storefront-primaryCta'?: Record<string, never>;
  'Storefront.secondaryCta'?: Record<string, never>;
  'Storefront-secondaryCta'?: Record<string, never>;
  'Storefront.subtitle'?: Record<string, never>;
  'Storefront-subtitle'?: Record<string, never>;
  'Storefront.title'?: Record<string, never>;
  'Storefront-title'?: Record<string, never>;
}
