use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(RegistryPublishRequests::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RegistryPublishRequests::Id)
                            .string_len(64)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::Slug)
                            .string_len(96)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::Version)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::CrateName)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ModuleName)
                            .string_len(160)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::Description)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::Ownership)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::TrustLevel)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::License)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::EntryType)
                            .string_len(256)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::Marketplace)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::UiPackages)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::RequestedBy)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ApprovedBy)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::RejectedBy)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::RejectionReason)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ValidationWarnings)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ValidationErrors)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ArtifactPath)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ArtifactUrl)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ArtifactChecksumSha256)
                            .string_len(64)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ArtifactSize)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ArtifactContentType)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::SubmittedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ValidatedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::ApprovedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::PublishedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(RegistryPublishRequests::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_registry_publish_requests_slug_created")
                    .table(RegistryPublishRequests::Table)
                    .col(RegistryPublishRequests::Slug)
                    .col(RegistryPublishRequests::CreatedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(RegistryModuleReleases::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RegistryModuleReleases::Id)
                            .string_len(64)
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::RequestId)
                            .string_len(64)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::Slug)
                            .string_len(96)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::Version)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::CrateName)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::ModuleName)
                            .string_len(160)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::Description)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::Ownership)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::TrustLevel)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::License)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::EntryType)
                            .string_len(256)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::Marketplace)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::UiPackages)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::Publisher)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::ArtifactPath)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::ArtifactUrl)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::ChecksumSha256)
                            .string_len(64)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::ArtifactSize)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::YankedReason)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::YankedBy)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::YankedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::PublishedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(RegistryModuleReleases::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                RegistryModuleReleases::Table,
                                RegistryModuleReleases::RequestId,
                            )
                            .to(RegistryPublishRequests::Table, RegistryPublishRequests::Id)
                            .on_delete(ForeignKeyAction::SetNull),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_registry_module_releases_slug_published")
                    .table(RegistryModuleReleases::Table)
                    .col(RegistryModuleReleases::Slug)
                    .col(RegistryModuleReleases::PublishedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_registry_module_releases_slug_version")
                    .table(RegistryModuleReleases::Table)
                    .col(RegistryModuleReleases::Slug)
                    .col(RegistryModuleReleases::Version)
                    .unique()
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(RegistryModuleReleases::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(RegistryPublishRequests::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum RegistryPublishRequests {
    Table,
    Id,
    Slug,
    Version,
    CrateName,
    ModuleName,
    Description,
    Ownership,
    TrustLevel,
    License,
    EntryType,
    Marketplace,
    UiPackages,
    Status,
    RequestedBy,
    ApprovedBy,
    RejectedBy,
    RejectionReason,
    ValidationWarnings,
    ValidationErrors,
    ArtifactPath,
    ArtifactUrl,
    ArtifactChecksumSha256,
    ArtifactSize,
    ArtifactContentType,
    SubmittedAt,
    ValidatedAt,
    ApprovedAt,
    PublishedAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum RegistryModuleReleases {
    Table,
    Id,
    RequestId,
    Slug,
    Version,
    CrateName,
    ModuleName,
    Description,
    Ownership,
    TrustLevel,
    License,
    EntryType,
    Marketplace,
    UiPackages,
    Status,
    Publisher,
    ArtifactPath,
    ArtifactUrl,
    ChecksumSha256,
    ArtifactSize,
    YankedReason,
    YankedBy,
    YankedAt,
    PublishedAt,
    CreatedAt,
    UpdatedAt,
}
