#[path = "../../rustok-build/src/module_manifest_contribution.rs"]
pub mod module_manifest_contribution;

use module_manifest_contribution::normalize_module_contribution_manifest;
use serde_json::Value;
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::PathBuf;

const MODULE_MANIFEST_RELATIVE_PATH: &str = "../rustok-module.toml";
const GENERATED_FILE: &str = "forum_contribution_manifest.rs";
const FORUM_MODULE_ID: &str = "forum";
const FORUM_OWNER_PROVIDER: &str = "rustok.forum";
const WIDGET_CATALOG_ROLE: &str = "widget_catalog";
const WIDGET_PREVIEW_ROLE: &str = "widget_preview";
const OWNER_SCHEMA_REF_FORMAT: &str = "forum_widget_owner_schema_ref_v1";

fn main() {
    println!("cargo:rerun-if-changed={MODULE_MANIFEST_RELATIVE_PATH}");
    println!("cargo:rerun-if-changed=../../rustok-build/src/module_manifest_contribution.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let manifest_path = manifest_dir.join(MODULE_MANIFEST_RELATIVE_PATH);
    let source = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", manifest_path.display()));
    let normalized = normalize_module_contribution_manifest(&source)
        .unwrap_or_else(|error| {
            panic!(
                "invalid {} contribution metadata: {error}",
                manifest_path.display()
            )
        })
        .unwrap_or_else(|| {
            panic!(
                "{} must declare fba.builder_consumer.contribution_manifest",
                manifest_path.display()
            )
        });

    if normalized.module_id != FORUM_MODULE_ID {
        panic!(
            "Forum admin contribution generator requires module.slug='{FORUM_MODULE_ID}', got '{}'",
            normalized.module_id
        );
    }
    if normalized.owner_provider != FORUM_OWNER_PROVIDER {
        panic!(
            "Forum contribution owner provider must remain '{FORUM_OWNER_PROVIDER}', got '{}'",
            normalized.owner_provider
        );
    }
    let cargo_version = env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION");
    if normalized.owner_version != cargo_version {
        panic!(
            "Forum module.version '{}' must match rustok-forum-admin package version '{cargo_version}'",
            normalized.owner_version
        );
    }

    let catalog_role = required_role(&normalized, WIDGET_CATALOG_ROLE);
    let preview_role = required_role(&normalized, WIDGET_PREVIEW_ROLE);
    if catalog_role.provider != normalized.owner_provider
        || preview_role.provider != normalized.owner_provider
    {
        panic!(
            "Forum widget contributions must stay under owner provider '{}'",
            normalized.owner_provider
        );
    }
    if catalog_role.blocks.len() != 3 {
        panic!("Forum widget catalog contribution must declare exactly three canonical blocks");
    }
    if !preview_role.blocks.is_empty() {
        panic!("Forum widget preview contribution must not duplicate block definitions");
    }

    let catalog = find_admin_contribution(&normalized.admin, &catalog_role.id);
    let preview = find_admin_contribution(&normalized.admin, &preview_role.id);
    validate_widget_contracts(catalog, preview, &catalog_role.blocks);

    let manifest_json = normalized
        .manifest_json()
        .expect("generated Forum contribution manifest must serialize");

    let mut generated = String::from(
        "// @generated by rustok-forum-admin/build.rs through rustok-build module metadata tooling from ../rustok-module.toml.\n// Do not edit by hand.\n\n",
    );
    push_str_const(&mut generated, "FORUM_MODULE_ID", &normalized.module_id);
    push_str_const(
        &mut generated,
        "FORUM_OWNER_PROVIDER",
        &normalized.owner_provider,
    );
    push_str_const(
        &mut generated,
        "FORUM_OWNER_PROVIDER_VERSION",
        &normalized.owner_version,
    );
    push_str_const(
        &mut generated,
        "FORUM_WIDGET_CONTRIBUTION_ID",
        &catalog_role.id,
    );
    push_str_const(
        &mut generated,
        "FORUM_WIDGET_PREVIEW_CONTRIBUTION_ID",
        &preview_role.id,
    );
    push_str_slice_const(
        &mut generated,
        "FORUM_BUILDER_CAPABILITIES",
        &normalized.builder_capabilities,
    );
    let permissions = normalized
        .required_permissions
        .iter()
        .cloned()
        .collect::<Vec<_>>();
    push_str_slice_const(
        &mut generated,
        "FORUM_REQUIRED_PERMISSIONS",
        &permissions,
    );
    push_str_slice_const(
        &mut generated,
        "FORUM_WIDGET_COMPONENT_TYPES",
        &catalog_role.blocks,
    );
    generated.push_str(&format!(
        "pub const GENERATED_FORUM_CONTRIBUTION_MANIFEST_JSON: &str = {manifest_json:?};\n"
    ));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join(GENERATED_FILE), generated)
        .expect("write generated Forum contribution manifest");
}

fn required_role<'a>(
    normalized: &'a module_manifest_contribution::NormalizedModuleContributionManifest,
    role: &str,
) -> &'a module_manifest_contribution::ContributionRoleExport {
    let value = normalized
        .role(role)
        .unwrap_or_else(|| panic!("contribution_manifest must declare role='{role}'"));
    if value.surface != "admin" {
        panic!("Forum contribution role '{role}' must remain on the admin surface");
    }
    value
}

fn find_admin_contribution<'a>(admin: &'a [Value], id: &str) -> &'a Value {
    admin
        .iter()
        .find(|value| value.get("id").and_then(Value::as_str) == Some(id))
        .unwrap_or_else(|| panic!("normalized Forum admin contribution '{id}' is missing"))
}

fn validate_widget_contracts(catalog: &Value, preview: &Value, blocks: &[String]) {
    let block_types = blocks.iter().cloned().collect::<BTreeSet<_>>();
    if block_types.len() != blocks.len() {
        panic!("Forum widget block ids must be unique");
    }

    let catalog_renderers = catalog
        .get("renderers")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[]);
    if !catalog_renderers.is_empty() {
        panic!("Forum widget catalog contribution must not bypass preview capability gating");
    }

    let editors = catalog
        .get("property_editors")
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("Forum widget catalog contribution must declare property editors"));
    let editor_types = editors
        .iter()
        .map(|editor| required_json_string(editor, "component_type", "property editor"))
        .collect::<BTreeSet<_>>();
    if editor_types != block_types {
        panic!("Forum property-editor component types must exactly match canonical widget block ids");
    }
    for editor in editors {
        let schema = editor
            .get("property_schema")
            .and_then(Value::as_object)
            .unwrap_or_else(|| panic!("Forum property editor must declare an owner schema reference"));
        if schema.get("format").and_then(Value::as_str) != Some(OWNER_SCHEMA_REF_FORMAT) {
            panic!("Forum property editor schema must use {OWNER_SCHEMA_REF_FORMAT}");
        }
        for key in [
            "schema_id",
            "catalog_endpoint",
            "validate_endpoint",
            "owner_data_state",
        ] {
            let value = schema
                .get(key)
                .and_then(Value::as_str)
                .map(str::trim)
                .unwrap_or_default();
            if value.is_empty() {
                panic!("Forum property editor owner schema reference requires non-empty {key}");
            }
        }
    }

    let preview_blocks = preview
        .get("blocks")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[]);
    if !preview_blocks.is_empty() {
        panic!("Forum widget preview contribution must not duplicate block definitions");
    }
    let preview_editors = preview
        .get("property_editors")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[]);
    if !preview_editors.is_empty() {
        panic!("Forum widget preview contribution must not duplicate property editors");
    }
    let renderers = preview
        .get("renderers")
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("Forum widget preview contribution must declare renderers"));
    let renderer_types = renderers
        .iter()
        .map(|renderer| required_json_string(renderer, "component_type", "renderer"))
        .collect::<BTreeSet<_>>();
    if renderer_types != block_types {
        panic!("Forum renderer component types must exactly match canonical widget block ids");
    }
    for renderer in renderers {
        let presentations = renderer
            .get("presentations")
            .and_then(Value::as_array)
            .unwrap_or_else(|| panic!("Forum widget renderer must declare presentations"))
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .unwrap_or_else(|| panic!("Forum renderer presentations must be strings"))
                    .to_string()
            })
            .collect::<BTreeSet<_>>();
        let expected = ["full", "inline", "preview", "read_only"]
            .into_iter()
            .map(ToString::to_string)
            .collect::<BTreeSet<_>>();
        if presentations != expected {
            panic!("Forum widget renderer must support full/inline/preview/read_only presentations");
        }
    }
}

fn required_json_string(value: &Value, key: &str, label: &str) -> String {
    value
        .get(key)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToString::to_string)
        .unwrap_or_else(|| panic!("Forum {label} requires non-empty {key}"))
}

fn push_str_const(output: &mut String, name: &str, value: &str) {
    output.push_str(&format!("pub const {name}: &str = {value:?};\n"));
}

fn push_str_slice_const(output: &mut String, name: &str, values: &[String]) {
    output.push_str(&format!("pub const {name}: &[&str] = &["));
    for value in values {
        output.push_str(&format!("{value:?},"));
    }
    output.push_str("];\n");
}
