use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(MarketplaceListings::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MarketplaceListings::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::SellerId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::MasterProductId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::MasterVariantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::SellerSku)
                            .string_len(120)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::MarketSlug)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::ChannelSlug)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::ApprovalStatus)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(ColumnDef::new(MarketplaceListings::ApprovalNote).text())
                    .col(ColumnDef::new(MarketplaceListings::SuspensionReason).text())
                    .col(
                        ColumnDef::new(MarketplaceListings::CurrentTermsVersion)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::PublishedAt).timestamp_with_time_zone(),
                    )
                    .col(ColumnDef::new(MarketplaceListings::ApprovedAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(MarketplaceListings::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListings::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        for index in [
            Index::create()
                .name("uq_marketplace_listings_tenant_id")
                .table(MarketplaceListings::Table)
                .col(MarketplaceListings::TenantId)
                .col(MarketplaceListings::Id)
                .unique()
                .to_owned(),
            Index::create()
                .name("uq_marketplace_listings_scope")
                .table(MarketplaceListings::Table)
                .col(MarketplaceListings::TenantId)
                .col(MarketplaceListings::SellerId)
                .col(MarketplaceListings::MasterVariantId)
                .col(MarketplaceListings::MarketSlug)
                .col(MarketplaceListings::ChannelSlug)
                .unique()
                .to_owned(),
            Index::create()
                .name("uq_marketplace_listings_seller_sku")
                .table(MarketplaceListings::Table)
                .col(MarketplaceListings::TenantId)
                .col(MarketplaceListings::SellerId)
                .col(MarketplaceListings::SellerSku)
                .unique()
                .to_owned(),
            Index::create()
                .name("idx_marketplace_listings_variant_scope")
                .table(MarketplaceListings::Table)
                .col(MarketplaceListings::TenantId)
                .col(MarketplaceListings::MasterVariantId)
                .col(MarketplaceListings::MarketSlug)
                .col(MarketplaceListings::ChannelSlug)
                .col(MarketplaceListings::Status)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        manager
            .create_table(
                Table::create()
                    .table(MarketplaceListingTerms::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MarketplaceListingTerms::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingTerms::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingTerms::ListingId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingTerms::Version)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(MarketplaceListingTerms::PricingReference).string_len(191))
                    .col(
                        ColumnDef::new(MarketplaceListingTerms::InventoryReference).string_len(191),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingTerms::FulfillmentProfileSlug)
                            .string_len(120),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingTerms::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingTerms::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_marketplace_listing_terms_tenant_listing")
                            .from(
                                MarketplaceListingTerms::Table,
                                MarketplaceListingTerms::TenantId,
                            )
                            .from_col(MarketplaceListingTerms::ListingId)
                            .to(MarketplaceListings::Table, MarketplaceListings::TenantId)
                            .to_col(MarketplaceListings::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("uq_marketplace_listing_terms_version")
                    .table(MarketplaceListingTerms::Table)
                    .col(MarketplaceListingTerms::TenantId)
                    .col(MarketplaceListingTerms::ListingId)
                    .col(MarketplaceListingTerms::Version)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(MarketplaceListingCommandReceipts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::ActorId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::IdempotencyKey)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::CommandKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::RequestHash)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::ResponseJson)
                            .json_binary(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(MarketplaceListingCommandReceipts::CompletedAt)
                            .timestamp_with_time_zone(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("uq_marketplace_listing_command_receipt_key")
                    .table(MarketplaceListingCommandReceipts::Table)
                    .col(MarketplaceListingCommandReceipts::TenantId)
                    .col(MarketplaceListingCommandReceipts::IdempotencyKey)
                    .unique()
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(MarketplaceListingCommandReceipts::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(MarketplaceListingTerms::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(MarketplaceListings::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
enum MarketplaceListings {
    Table,
    Id,
    TenantId,
    SellerId,
    MasterProductId,
    MasterVariantId,
    SellerSku,
    MarketSlug,
    ChannelSlug,
    Status,
    ApprovalStatus,
    ApprovalNote,
    SuspensionReason,
    CurrentTermsVersion,
    Metadata,
    PublishedAt,
    ApprovedAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum MarketplaceListingTerms {
    Table,
    Id,
    TenantId,
    ListingId,
    Version,
    PricingReference,
    InventoryReference,
    FulfillmentProfileSlug,
    Metadata,
    CreatedAt,
}

#[derive(Iden)]
enum MarketplaceListingCommandReceipts {
    Table,
    Id,
    TenantId,
    ActorId,
    IdempotencyKey,
    CommandKind,
    RequestHash,
    Status,
    ResponseJson,
    CreatedAt,
    CompletedAt,
}
