use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(MarketplaceOrderAllocations::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::OrderId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::OrderLineItemId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::SellerId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::ListingId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::MasterProductId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::MasterVariantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::Quantity)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::CurrencyCode)
                            .string_len(3)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::UnitAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::SubtotalAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::DiscountAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::TaxAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::TotalAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::ListingTermsVersion)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::PricingReference)
                            .string_len(191),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::InventoryReference)
                            .string_len(191),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::FulfillmentProfileSlug)
                            .string_len(120),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(MarketplaceOrderAllocations::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        for index in [
            Index::create()
                .name("uq_marketplace_order_allocations_line")
                .table(MarketplaceOrderAllocations::Table)
                .col(MarketplaceOrderAllocations::TenantId)
                .col(MarketplaceOrderAllocations::OrderLineItemId)
                .unique()
                .to_owned(),
            Index::create()
                .name("idx_marketplace_order_allocations_order")
                .table(MarketplaceOrderAllocations::Table)
                .col(MarketplaceOrderAllocations::TenantId)
                .col(MarketplaceOrderAllocations::OrderId)
                .col(MarketplaceOrderAllocations::Id)
                .to_owned(),
            Index::create()
                .name("idx_marketplace_order_allocations_seller")
                .table(MarketplaceOrderAllocations::Table)
                .col(MarketplaceOrderAllocations::TenantId)
                .col(MarketplaceOrderAllocations::SellerId)
                .col(MarketplaceOrderAllocations::Status)
                .col(MarketplaceOrderAllocations::CreatedAt)
                .to_owned(),
            Index::create()
                .name("idx_marketplace_order_allocations_listing")
                .table(MarketplaceOrderAllocations::Table)
                .col(MarketplaceOrderAllocations::TenantId)
                .col(MarketplaceOrderAllocations::ListingId)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        manager
            .create_table(
                Table::create()
                    .table(MarketplaceAllocationReceipts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::ActorId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::IdempotencyKey)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::RequestKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::RequestHash)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(ColumnDef::new(MarketplaceAllocationReceipts::ResponseJson).json_binary())
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(MarketplaceAllocationReceipts::CompletedAt)
                            .timestamp_with_time_zone(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_marketplace_allocation_receipt_key")
                    .table(MarketplaceAllocationReceipts::Table)
                    .col(MarketplaceAllocationReceipts::TenantId)
                    .col(MarketplaceAllocationReceipts::IdempotencyKey)
                    .unique()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(MarketplaceAllocationReceipts::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(MarketplaceOrderAllocations::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
enum MarketplaceOrderAllocations {
    Table,
    Id,
    TenantId,
    OrderId,
    OrderLineItemId,
    SellerId,
    ListingId,
    MasterProductId,
    MasterVariantId,
    Quantity,
    CurrencyCode,
    UnitAmount,
    SubtotalAmount,
    DiscountAmount,
    TaxAmount,
    TotalAmount,
    ListingTermsVersion,
    PricingReference,
    InventoryReference,
    FulfillmentProfileSlug,
    Status,
    Metadata,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum MarketplaceAllocationReceipts {
    Table,
    Id,
    TenantId,
    ActorId,
    IdempotencyKey,
    RequestKind,
    RequestHash,
    Status,
    ResponseJson,
    CreatedAt,
    CompletedAt,
}
