use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(MarketplaceCommissionRules::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::RuleKey)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::Version)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(MarketplaceCommissionRules::SellerId).uuid())
                    .col(ColumnDef::new(MarketplaceCommissionRules::ListingId).uuid())
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::RateBps)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::FixedAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(MarketplaceCommissionRules::CurrencyCode).string_len(3))
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::Priority)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::EffectiveFrom)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::EffectiveUntil)
                            .timestamp_with_time_zone(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionRules::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        for index in [
            Index::create()
                .name("uq_marketplace_commission_rule_version")
                .table(MarketplaceCommissionRules::Table)
                .col(MarketplaceCommissionRules::TenantId)
                .col(MarketplaceCommissionRules::RuleKey)
                .col(MarketplaceCommissionRules::Version)
                .unique()
                .to_owned(),
            Index::create()
                .name("idx_marketplace_commission_rule_listing")
                .table(MarketplaceCommissionRules::Table)
                .col(MarketplaceCommissionRules::TenantId)
                .col(MarketplaceCommissionRules::ListingId)
                .col(MarketplaceCommissionRules::Status)
                .col(MarketplaceCommissionRules::Priority)
                .to_owned(),
            Index::create()
                .name("idx_marketplace_commission_rule_seller")
                .table(MarketplaceCommissionRules::Table)
                .col(MarketplaceCommissionRules::TenantId)
                .col(MarketplaceCommissionRules::SellerId)
                .col(MarketplaceCommissionRules::Status)
                .col(MarketplaceCommissionRules::Priority)
                .to_owned(),
            Index::create()
                .name("idx_marketplace_commission_rule_global")
                .table(MarketplaceCommissionRules::Table)
                .col(MarketplaceCommissionRules::TenantId)
                .col(MarketplaceCommissionRules::Status)
                .col(MarketplaceCommissionRules::EffectiveFrom)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        manager
            .create_table(
                Table::create()
                    .table(MarketplaceCommissionAssessments::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::AllocationId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::OrderId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::OrderLineItemId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::SellerId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::ListingId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::RuleId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::RuleKey)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::RuleVersion)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::CurrencyCode)
                            .string_len(3)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::AllocationTotalAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::RateBps)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::FixedAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::CommissionAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::SellerProceedsAmount)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::AssessedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionAssessments::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        for index in [
            Index::create()
                .name("uq_marketplace_commission_assessment_allocation")
                .table(MarketplaceCommissionAssessments::Table)
                .col(MarketplaceCommissionAssessments::TenantId)
                .col(MarketplaceCommissionAssessments::AllocationId)
                .unique()
                .to_owned(),
            Index::create()
                .name("idx_marketplace_commission_assessment_order")
                .table(MarketplaceCommissionAssessments::Table)
                .col(MarketplaceCommissionAssessments::TenantId)
                .col(MarketplaceCommissionAssessments::OrderId)
                .col(MarketplaceCommissionAssessments::Id)
                .to_owned(),
            Index::create()
                .name("idx_marketplace_commission_assessment_seller")
                .table(MarketplaceCommissionAssessments::Table)
                .col(MarketplaceCommissionAssessments::TenantId)
                .col(MarketplaceCommissionAssessments::SellerId)
                .col(MarketplaceCommissionAssessments::Status)
                .col(MarketplaceCommissionAssessments::AssessedAt)
                .to_owned(),
        ] {
            manager.create_index(index).await?;
        }

        manager
            .create_table(
                Table::create()
                    .table(MarketplaceCommissionReceipts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::ActorId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::IdempotencyKey)
                            .string_len(191)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::CommandKind)
                            .string_len(80)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::RequestHash)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::Status)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(ColumnDef::new(MarketplaceCommissionReceipts::ResponseKind).string_len(32))
                    .col(ColumnDef::new(MarketplaceCommissionReceipts::ResponseJson).json_binary())
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(MarketplaceCommissionReceipts::CompletedAt)
                            .timestamp_with_time_zone(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_marketplace_commission_receipt_key")
                    .table(MarketplaceCommissionReceipts::Table)
                    .col(MarketplaceCommissionReceipts::TenantId)
                    .col(MarketplaceCommissionReceipts::IdempotencyKey)
                    .unique()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(MarketplaceCommissionReceipts::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(MarketplaceCommissionAssessments::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(MarketplaceCommissionRules::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
enum MarketplaceCommissionRules {
    Table,
    Id,
    TenantId,
    RuleKey,
    Version,
    SellerId,
    ListingId,
    RateBps,
    FixedAmount,
    CurrencyCode,
    Priority,
    EffectiveFrom,
    EffectiveUntil,
    Status,
    Metadata,
    CreatedAt,
}

#[derive(Iden)]
enum MarketplaceCommissionAssessments {
    Table,
    Id,
    TenantId,
    AllocationId,
    OrderId,
    OrderLineItemId,
    SellerId,
    ListingId,
    RuleId,
    RuleKey,
    RuleVersion,
    CurrencyCode,
    AllocationTotalAmount,
    RateBps,
    FixedAmount,
    CommissionAmount,
    SellerProceedsAmount,
    Status,
    Metadata,
    AssessedAt,
    CreatedAt,
}

#[derive(Iden)]
enum MarketplaceCommissionReceipts {
    Table,
    Id,
    TenantId,
    ActorId,
    IdempotencyKey,
    CommandKind,
    RequestHash,
    Status,
    ResponseKind,
    ResponseJson,
    CreatedAt,
    CompletedAt,
}
