use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct ScriptsMigration;

#[async_trait::async_trait]
impl MigrationTrait for ScriptsMigration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Scripts::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(Scripts::Id).uuid().not_null().primary_key())
                    .col(ColumnDef::new(Scripts::TenantId).uuid().not_null())
                    .col(ColumnDef::new(Scripts::Name).string_len(255).not_null())
                    .col(ColumnDef::new(Scripts::Description).text())
                    .col(ColumnDef::new(Scripts::Workspace).json_binary().not_null())
                    .col(
                        ColumnDef::new(Scripts::TriggerType)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Scripts::TriggerConfig)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Scripts::Status)
                            .string_len(32)
                            .not_null()
                            .default("draft"),
                    )
                    .col(
                        ColumnDef::new(Scripts::Version)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(Scripts::RunAsSystem)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Scripts::Permissions)
                            .json_binary()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Scripts::AuthorId).string_len(255))
                    .col(
                        ColumnDef::new(Scripts::SourceProvenance)
                            .json_binary()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Scripts::ParentReleaseSlug).string_len(128))
                    .col(ColumnDef::new(Scripts::ParentReleaseVersion).string_len(64))
                    .col(ColumnDef::new(Scripts::ParentReleaseDigest).string_len(71))
                    .col(
                        ColumnDef::new(Scripts::ErrorCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(Scripts::LastErrorAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(Scripts::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Scripts::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .name("uidx_scripts_tenant_name")
                            .col(Scripts::TenantId)
                            .col(Scripts::Name),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_scripts_tenant_trigger_status")
                    .table(Scripts::Table)
                    .col(Scripts::TenantId)
                    .col(Scripts::TriggerType)
                    .col(Scripts::Status)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ScriptTombstones::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ScriptTombstones::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ScriptTombstones::TenantId).uuid().not_null())
                    .col(
                        ColumnDef::new(ScriptTombstones::DeletedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptTombstones::DeletedBy)
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptTombstones::DeleteReason)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptTombstones::IdempotencyKey)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptTombstones::RequestDigest)
                            .string_len(71)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptTombstones::RetentionPolicy)
                            .string_len(32)
                            .not_null()
                            .default("retain_until"),
                    )
                    .col(ColumnDef::new(ScriptTombstones::RetainUntil).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(ScriptTombstones::RetentionRevision)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_alloy_script_tombstones_deleted_at")
                    .table(ScriptTombstones::Table)
                    .col(ScriptTombstones::DeletedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_alloy_script_tombstones_retention")
                    .table(ScriptTombstones::Table)
                    .col(ScriptTombstones::RetentionPolicy)
                    .col(ScriptTombstones::RetainUntil)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ScriptRetentionReceipts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::ScriptId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::Action)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::ActorId)
                            .string_len(255)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::IdempotencyKey)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::RequestDigest)
                            .string_len(71)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::DeletionRequestDigest)
                            .string_len(71)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::RetentionPolicy)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::RetainUntil)
                            .timestamp_with_time_zone(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::RetentionRevision)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptRetentionReceipts::RecordedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .name("uidx_alloy_script_retention_receipts_idempotency")
                            .col(ScriptRetentionReceipts::TenantId)
                            .col(ScriptRetentionReceipts::ScriptId)
                            .col(ScriptRetentionReceipts::DeletionRequestDigest)
                            .col(ScriptRetentionReceipts::IdempotencyKey),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ScriptPurgeReceipts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::ScriptId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::RetentionPolicy)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::RetainUntil)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::PurgedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::SourceRevisionCount)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::ReviewCount)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::TestRunCount)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScriptPurgeReceipts::DeletionRequestDigest)
                            .string_len(71)
                            .not_null(),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .name("uidx_alloy_script_purge_receipts_deletion")
                            .col(ScriptPurgeReceipts::TenantId)
                            .col(ScriptPurgeReceipts::ScriptId)
                            .col(ScriptPurgeReceipts::DeletionRequestDigest),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(ScriptRetentionReceipts::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(ScriptPurgeReceipts::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(ScriptTombstones::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Scripts::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum Scripts {
    Table,
    Id,
    TenantId,
    Name,
    Description,
    Workspace,
    TriggerType,
    TriggerConfig,
    Status,
    Version,
    RunAsSystem,
    Permissions,
    AuthorId,
    SourceProvenance,
    ParentReleaseSlug,
    ParentReleaseVersion,
    ParentReleaseDigest,
    ErrorCount,
    LastErrorAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum ScriptTombstones {
    #[iden = "alloy_script_tombstones"]
    Table,
    Id,
    TenantId,
    DeletedAt,
    DeletedBy,
    DeleteReason,
    IdempotencyKey,
    RequestDigest,
    RetentionPolicy,
    RetainUntil,
    RetentionRevision,
}

#[derive(Iden)]
enum ScriptRetentionReceipts {
    #[iden = "alloy_script_retention_receipts"]
    Table,
    Id,
    ScriptId,
    TenantId,
    Action,
    ActorId,
    IdempotencyKey,
    RequestDigest,
    DeletionRequestDigest,
    RetentionPolicy,
    RetainUntil,
    RetentionRevision,
    RecordedAt,
}

#[derive(Iden)]
enum ScriptPurgeReceipts {
    #[iden = "alloy_script_purge_receipts"]
    Table,
    Id,
    ScriptId,
    TenantId,
    RetentionPolicy,
    RetainUntil,
    PurgedAt,
    SourceRevisionCount,
    ReviewCount,
    TestRunCount,
    DeletionRequestDigest,
}
