/**
 * FTL AST Key & Variable Extractor for TypeScript declaration generation.
 */

export interface ExtractedMessage {
  id: string;
  dotId: string;
  attributes: string[];
  variables: string[];
}

export function extractMessagesFromFtl(ftlContent: string): ExtractedMessage[] {
  const messages: ExtractedMessage[] = [];
  const lines = ftlContent.split(/\r?\n/);

  let currentMsg: ExtractedMessage | null = null;

  for (const line of lines) {
    // Comment or empty line
    if (line.startsWith('#') || !line.trim()) {
      continue;
    }

    // Message definition: `my-message-id = ...`
    const msgMatch = line.match(/^([a-zA-Z][a-zA-Z0-9_-]*)\s*=/);
    if (msgMatch) {
      const id = msgMatch[1];
      const dotId = id.replace(/-/g, '.');
      currentMsg = {
        id,
        dotId,
        attributes: [],
        variables: [],
      };
      messages.push(currentMsg);

      // Extract inline variables: `{$name}` or `{ $name }`
      const varMatches = line.matchAll(/\{\s*\$([a-zA-Z0-9_-]+)/g);
      for (const vm of varMatches) {
        if (!currentMsg.variables.includes(vm[1])) {
          currentMsg.variables.push(vm[1]);
        }
      }
      continue;
    }

    // Attribute definition: `  .label = ...`
    const attrMatch = line.match(/^\s+\.([a-zA-Z][a-zA-Z0-9_-]*)\s*=/);
    if (attrMatch && currentMsg) {
      currentMsg.attributes.push(attrMatch[1]);
      continue;
    }

    // Continuation line with variables
    if (currentMsg) {
      const varMatches = line.matchAll(/\{\s*\$([a-zA-Z0-9_-]+)/g);
      for (const vm of varMatches) {
        if (!currentMsg.variables.includes(vm[1])) {
          currentMsg.variables.push(vm[1]);
        }
      }
    }
  }

  return messages;
}

export function generateTypeDeclarations(
  ftlContents: string | readonly string[],
  options: { exportName?: string } = {}
): string {
  const contents = Array.isArray(ftlContents) ? ftlContents : [ftlContents];
  const allMessages: ExtractedMessage[] = [];
  const seenIds = new Set<string>();

  for (const content of contents) {
    const extracted = extractMessagesFromFtl(content);
    for (const msg of extracted) {
      if (!seenIds.has(msg.id)) {
        seenIds.add(msg.id);
        allMessages.push(msg);
      }
    }
  }

  // Sort messages
  allMessages.sort((a, b) => a.id.localeCompare(b.id));

  const keyUnion = allMessages
    .flatMap((m) => [`  | '${m.id}'`, `  | '${m.dotId}'`])
    .join('\n');

  const argsEntries = allMessages.map((m) => {
    if (m.variables.length === 0) {
      return `  '${m.dotId}'?: Record<string, never>;\n  '${m.id}'?: Record<string, never>;`;
    }
    const varsType = m.variables
      .map((v) => `${v}: string | number | Date`)
      .join('; ');
    return `  '${m.dotId}': { ${varsType} };\n  '${m.id}': { ${varsType} };`;
  });

  return `// Auto-generated by next-fluent typegen. DO NOT EDIT DIRECTLY.
/* eslint-disable */

export type AppMessageKey =
${keyUnion || "  | string"};

export interface AppMessageArgs {
${argsEntries.join('\n')}
}
`;
}
